- Cargo.lock
- Cargo.toml
- README.md
- src/cmd/deploy.rs
- src/cmd/instantiate.rs
- src/cmd/mod.rs
- src/main.rs
Closes #4 
For now it accepts just raw hex encoded `data` - in the example above the data is the hex encoded selector of the no args constructor, which I extracted from the metadata json.
> Implement instantiate command

- Cargo.lock
- Cargo.toml
- src/cmd/build.rs
- src/cmd/deploy.rs
- src/cmd/instantiate.rs
- src/cmd/metadata.rs
- src/cmd/new.rs
- src/main.rs
> Remove ink! abstraction layer

- Cargo.lock
- Cargo.toml
- src/cmd/deploy.rs
- src/cmd/instantiate.rs
New submit and watch API, and now works with latest substrate
> Update to latest subxt

- Cargo.lock
- Cargo.toml
- src/cmd/deploy.rs
- src/cmd/instantiate.rs
- src/cmd/mod.rs
Also factors out common extrinsic submission, and updates to latest substrate
> Update to latest subxt with async/await

- .gitlab-ci.yml
- src/cmd/extrinsics.rs
- src/cmd/mod.rs
- src/main.rs
> Fix default features build

- template/.ink/abi_gen/Cargo.toml
- template/Cargo.toml
- template/lib.rs
Link to PR: https://github.com/paritytech/ink/pull/312
Implements proposed adjustments as noted down in https://github.com/paritytech/cargo-contract/issues/24.
Merge as soon as https://github.com/paritytech/ink/pull/312 merges.
> Update template for upcoming merge of ink! PR #312

- template/.ink/abi_gen/main.rs
> Replace ink_lang2 with ink_lang

- .github/workflows/release-bot.yml
To automatically post release updates to Riot room
> Added github workflow for release bot

- Cargo.lock
- Cargo.toml
- template/Cargo.toml
- parity-scale-codec 1.2
- subxt latest commit
- sp-core alpha.3
> Upgrade dependencies

- template/.ink/abi_gen/Cargo.toml
- template/Cargo.toml
Follow-up for https://github.com/paritytech/ink/pull/353.
> Update template to ink! 2.0 dependencies

- Cargo.lock
- Cargo.toml
- src/cmd/deploy.rs
- src/cmd/instantiate.rs
- src/main.rs
> Update to latest subxt release

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
* Update new command template to ink! 3.0-rc2 [#85](https://github.com/paritytech/cargo-contract/pull/85)
> Release v0.7.1

- src/cmd/build.rs
- src/cmd/metadata.rs
- src/crate_metadata.rs
- src/main.rs
> Put build artifacts under `target/ink/`

- src/cmd/new.rs
Unified function call
https://github.com/paritytech/cargo-contract/blob/4c156d98176ca767c2cc62cab03d091297ca4e88/src/cmd/new.rs#L121-L122
> delete cmd::new:: in new.rs

- src/main.rs
tst01/target/ink/tst01.wasm
so delete  -pruned
> update wasm-path usage name

- src/crate_metadata.rs
- src/workspace/manifest.rs
- src/workspace/mod.rs
> feat ok_or warning

- src/util.rs
replace unwrap_or with unwrap_or_else
> feat unwrap_or warning

- build.rs
- metadata/lib.rs
- src/cmd/build.rs
- src/cmd/deploy.rs
- src/cmd/instantiate.rs
- src/cmd/metadata.rs
- src/cmd/mod.rs
- src/cmd/new.rs
- src/crate_metadata.rs
- src/main.rs
- src/util.rs
- src/workspace/manifest.rs
- src/workspace/metadata.rs
- src/workspace/mod.rs
- src/workspace/profile.rs
> 2021 file headers

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- Fix linker error when building complex contracts - [#199](https://github.com/paritytech/cargo-contract/pull/199)
> Release 0.9.1

- .gitlab-ci.yml
I've added clippy to our contracts CI image in https://github.com/paritytech/scripts/pull/276.
> Add clippy to CI

- README.md
- src/cmd/build.rs
Readme preview [here](https://github.com/paritytech/cargo-contract/tree/cmichi-improve-wasm-opt-errors).
> Improve `wasm-opt` error output

- templates/new/_Cargo.toml
I missed the template update in #250, sorry!
> Update scale version in template

- Cargo.lock
- Cargo.toml
- templates/new/_Cargo.toml
`bitvec` 0.20.2 has been released, the issue has been fixed.
> Remove `funty` pin

- .gitlab-ci.yml
- src/cmd/build.rs
- src/cmd/deploy.rs
- src/cmd/instantiate.rs
- src/cmd/metadata.rs
- src/workspace/manifest.rs
The clippy CI job wasn't applied to testing code. I fixed that and also corrected all clippy lints that came up due to this.
> Apply clippy to all code

- README.md
> Mention the contracts Docker image in the project README

- CHANGELOG.md
- templates/new/_Cargo.toml
Follow-up to https://github.com/paritytech/ink/pull/1034.
> Disable overflow checks

- CODEOWNERS
This PR add core team members as codeowners
> Add core team as codeowners

- src/crate_metadata.rs
- src/main.rs
See here for the complete error output which is currently happening on `master`: https://gitlab.parity.io/parity/cargo-contract/-/jobs/1284437.
> Fix `clippy::single_char_pattern`

- .github/workflows/macos.yml
- .github/workflows/windows.yml
For https://github.com/paritytech/ci_cd/issues/303.
> Output `cc` and `clang` version

- CHANGELOG.md
- templates/new/_Cargo.toml
Follow-up to https://github.com/paritytech/ink/pull/1049.
> Revert disabling overflow checks

- .github/workflows/dependabot-auto-merge.yml
Finally closing https://github.com/paritytech/cargo-contract/issues/331.
Let's just try it for PATCH updates at first.
> Auto-merge dependabot PR's for PATCH updates

- src/cmd/extrinsics/instantiate.rs
- src/cmd/extrinsics/transcode/encode.rs
- src/cmd/extrinsics/upload.rs
Noticed causing https://github.com/paritytech/cargo-contract/pull/455 CI to fail.
> Fix clippy suggestions

- README.md
A little correction in the document.
> fix(readme): correct guide number.

- README.md
openssl is required to build cargo-dylint
> Add missing dep

- src/cmd/extrinsics/transcode/mod.rs
Fixes https://github.com/paritytech/cargo-contract/issues/561
> Make sure constructor selector is looking for the exact function name

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
[Preview here](https://github.com/paritytech/cargo-contract/blob/cmichi-release-v1.4.0/CHANGELOG.md).
> Release v1.4.0

- .gitlab-ci.yml
Reuse `cargo` directories from `master`'s `clippy` too.
> Instrument `clippy` job with `rusty-cachier`

- src/cmd/extrinsics/call.rs
- src/cmd/extrinsics/instantiate.rs
- src/cmd/extrinsics/mod.rs
- src/cmd/extrinsics/upload.rs
> Manually convert Url::url to String in order to include the default port

- README.md
The app is now available at https://contracts-ui.substrate.io/
> Update Contracts UI link

- src/util.rs
- transcode/src/util.rs
> simplify hex parsing

- .github/workflows/windows.yml
> :t-rex: update windows CI dylint version

- .github/workflows/windows.yml
> Fix GHA syntax

- README.md
Following up on #706 
[preview](https://github.com/paritytech/cargo-contract/tree/aj/readme-ci-badges)
> Update README CI status badges

- crates/cargo-contract/src/cmd/extrinsics/call.rs
- crates/cargo-contract/src/cmd/extrinsics/error.rs
- crates/cargo-contract/src/cmd/extrinsics/instantiate.rs
- crates/cargo-contract/src/cmd/extrinsics/mod.rs
- crates/cargo-contract/src/cmd/extrinsics/upload.rs
- crates/cargo-contract/src/cmd/mod.rs
- crates/cargo-contract/src/main.rs
Suggestions for #722, feel free to ignore, merge or modify as you choose. **NOT TESTED**
> Suggested unification of error handling for #722

- Cargo.lock
- crates/cargo-contract/src/cmd/extrinsics/upload.rs
- crates/metadata/Cargo.toml
- crates/metadata/src/lib.rs
- crates/transcode/src/lib.rs
This PR adds printing of contract's code hash if cargo contract upload is called with a contract that has already been uploaded.
> Log code hash if contract is already uploaded.

- .gitlab-ci.yml
CI Tests on contracts-ci-linux image's tag for https://github.com/paritytech/cargo-contract/pull/857
> Fix Image Build For Release 1.5.x

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- metadata/Cargo.toml
This release contains fix for the #832 user reported bug
> Release v1.5.1

- README.md
Adding instructions on how to publish.
> Add publishing instructions to readme

- crates/build/src/args.rs
- crates/build/src/wasm_opt.rs
For latest rust version `1.68`
> Derive `Default` instances, make clippy happy :t-rex:

- .github/workflows/ci.yml
- crates/transcode/Cargo.toml
Also removes redundant `--default-features = false` from `sp-core` dependency
> Docs for CI `check` job

- CHANGELOG.md
- Cargo.lock
- crates/build/Cargo.toml
- crates/cargo-contract/Cargo.toml
- crates/metadata/Cargo.toml
- crates/transcode/Cargo.toml
Revert "Bump tracing from 0.1.37 to 0.1.38" - #1096
> `v2.2.1` Release

- docs/extrinsics.md
I have found dead links. Improved it.
> fix(link): subkey

- CODEOWNERS
Live long and prosper dude :vulcan_salute:
> :axe: @HCastano from CODEOWNERS

- README.md
manifest for paritytech/contracts-ci-linux:production not found: manifest unknown: manifest unknown
> docs: fix docker image name

- crates/build/src/lib.rs
RISC-V broke a while ago. Tiny fix.
> Fix RiscV build

- Cargo.lock
Closes #1339 
https://github.com/hermit-os/hermit-rs/compare/hermit-abi-0.3.2...hermit-abi-0.3.3
> bump hermit-abi

- crates/build/Cargo.toml
Fix misspelling of `default-features`
> Correct `wasm-opt` dependency default-features

- Cargo.lock
- crates/cargo-contract/src/cmd/storage.rs
- crates/extrinsics/Cargo.toml
- crates/extrinsics/src/contract_storage.rs
- crates/extrinsics/src/contract_storage_tests.rs
- crates/extrinsics/src/integration_tests.rs
- crates/extrinsics/src/lib.rs
> Add storage tests

- .github/workflows/ci.yml
- crates/extrinsics/src/integration_tests.rs
Closes #_
Add nextest to CI improving CI times by 30%
Add nextest to CI
Split test job into `integration-tests` and `tests` jobs
Prebuild test bins and share between jobs
> Add nextest to CI

- crates/cargo-contract/src/cmd/decode.rs
Closes #_
`Instantiate a contract`  was probably a copy paste from [here](https://github.com/paritytech/cargo-contract/blob/ee7667c19e0d4132ff6cbaa87192957ece7e0f67/crates/cargo-contract/src/main.rs#L127). 
- [y] My code follows the style guidelines of this project
- [n] I have added an entry to `CHANGELOG.md`
- [y] I have commented my code, particularly in hard-to-understand areas
- [y] I have added tests that prove my fix is effective or that my feature works
- [y] Any dependent changes have been merged and published in downstream modules
> Fixing incorrect doc

- crates/cargo-contract/tests/encode.rs
This should fix the failing CI in https://github.com/use-ink/cargo-contract/pull/1930.
> Implement CI fixes for #1930

- CHANGELOG.md
- Cargo.lock
- crates/build/Cargo.toml
- crates/cargo-contract/Cargo.toml
[Changelog Preview Link](https://github.com/use-ink/cargo-contract/blob/cmichi-update-changelog-2025-03-10/CHANGELOG.md).
> Update changelog with v6.0.0-alpha information

- Cargo.lock
- crates/build/src/lib.rs
- crates/build/src/workspace/profile.rs
- crates/cargo-contract/tests/decode.rs
- crates/cargo-contract/tests/encode.rs
- crates/cargo-contract/tests/verify.rs
- crates/extrinsics/src/env_check.rs
- crates/extrinsics/src/integration_tests.rs
- crates/transcode/src/env_types.rs
- crates/transcode/src/transcoder.rs
* https://github.com/paritytech/polkavm/issues/277
* https://github.com/paritytech/polkavm/issues/279
* https://github.com/paritytech/polkavm/commit/b0bdfe95692ad2472d297f2471e3d13a7d87550a
> Resolve todo's following bug fixes in `polkavm`

- crates/build/src/tests.rs
> chore: Re-enable build tests

- CHANGELOG.md
- Cargo.lock
- crates/build/src/crate_metadata.rs
- crates/build/src/new.rs
- crates/build/templates/new/_Cargo.toml
> Include ABI declaration in new project template

- Cargo.lock
- Cargo.toml
- crates/build/Cargo.toml
- crates/build/README.md
- crates/build/src/lint.rs
- crates/build/templates/new/_Cargo.toml
- crates/cargo-contract/Cargo.toml
- crates/extrinsics/Cargo.toml
- crates/extrinsics/src/integration_tests.rs
- crates/transcode/Cargo.toml
Synchronize with `polkadot-sdk/cb629d46ebf00aa65624013a61f9c69ebf02b0b4`.
Just seeing if the CI runs for now. Will switch back to ink! `master` branch.
> Synchronize with `polkadot-sdk/cb629d46ebf00aa65624013a61f9c69ebf02b0b4`

- CHANGELOG.md
- Cargo.lock
- crates/build/src/solidity_metadata/abi.rs
Follow up to https://github.com/use-ink/ink/pull/2583
> Add errors to Solidity metadata
