use-ink/cargo-contract

- Cargo.toml
- README.md
- src/cmd/build.rs
- src/cmd/deploy.rs
- src/cmd/mod.rs
- src/main.rs
Signed-off-by: koushiro <koushiro.cqx@gmail.com>
I think the `deploy` subcommand can be optional, because developers can send a RPC request to deploy the contract by using other tools.
> Add feature deploy

- .gitlab-ci.yml
- `contracts-ci-linux:latest` contains `fmt` now and
- unlike `ink-ci-linux` is updated nightly and
- has `stable` rust by default
> change the CI docker image

- Cargo.lock
- Cargo.toml
- src/cmd/build.rs
Closes #23.
- Requires `wasm-opt` to be installed on user machine
- If not present, then the build still "succeeds" but with a message encouraging the user to install the tool.
- Displays the size of the file before and after optimization
- Adds some pretty colours
> Add wasm-opt optimization build step

- CHANGELOG.md
- src/cmd/build.rs
Previously if the xbuild failed it would continue to the optimization step, which would of course fail too because of the missing artifact.
This PR fails the whole build with an error if the `xbuild` step fails.
> Fail the build if xbuild fails

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- src/cmd/build.rs
- src/cmd/metadata.rs
- src/workspace.rs
Fix for https://github.com/paritytech/ink/issues/391.
Recent nightly has broken since https://github.com/rust-lang/rust/pull/71925 (see https://github.com/rust-osdev/cargo-xbuild/issues/69#issuecomment-627231724)
- Upgrades version of `cargo-xbuild` which adds LTO flag to sysroot build: https://github.com/rust-osdev/cargo-xbuild/pull/71.
- Disables lto flag when generating metadata which fixes `file not recognized: File format not recognized`. rel: #40
> Fix LTO regressions in nightly toolchain

- Cargo.lock
- Cargo.toml
- src/cmd/build.rs
- src/workspace.rs
- template/_Cargo.toml
Rel #40, https://github.com/paritytech/ink/pull/448
If any of the following `[profile.release]` settings are missing, then they are added with the following preferred defaults:
```
[profile.release]
panic = "abort"
lto = true
opt-level = "z"
overflow-checks = true
codegen-units = 1
```
Any of the above that are manually specified are **not** overwritten. This allows manual control over e.g. `opt-level` where in some cases `opt-level = 3` might result in a smaller binary size.  
**Template changes:**
- Remove `[profile.release]` section
- ~~Use `scale-info` from crates.io instead of `type-metadata`~~ (reverted: requires ink! 3 release)
> Add preferred default release profile settings

- .rustfmt.toml
- FILE_HEADER
- build.rs
- src/cmd/build.rs
- src/cmd/deploy.rs
- src/cmd/instantiate.rs
- src/cmd/metadata.rs
- src/cmd/mod.rs
- src/cmd/new.rs
- src/main.rs
- src/util.rs
- src/workspace/manifest.rs
- src/workspace/metadata.rs
- src/workspace/mod.rs
- src/workspace/profile.rs
- Removes some legacy references from when the files were copied from `ink!`.
- Adds a `cargo fmt` check which ensures the file header format is adhered to.
> Add file header check, update file headers

- Cargo.lock
- Cargo.toml
- README.md
Fixes #70.
Upgrades to `cargo-xbuild 0.6.0` which includes https://github.com/rust-osdev/cargo-xbuild/pull/87. This makes it compatible with the new `rust-src` layout here https://github.com/rust-lang/rust/pull/73265.
I will merge this once there is a new `nightly` > 2020-07-30 which includes `rustfmt`: https://rust-lang.github.io/rustup-components-history/
> Upgrade cargo-xbuild and other dependencies

- src/crate_metadata.rs
- src/workspace/manifest.rs
Broken by upgrading `cargo-metadata` in #71
> Fix ManifestPath compiler errors

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- README.md
- build.rs
- metadata/README.md
- src/cmd/new.rs
- templates/new/_Cargo.toml
* Fix deprecation warnings [#82](https://github.com/paritytech/cargo-contract/pull/82)
* Use ink 3.0.0-rc1 [#82](https://github.com/paritytech/cargo-contract/pull/82)
* [template] now uses ink_env and ink_storage [#81](https://github.com/paritytech/cargo-contract/pull/81)
* Update new command template to ink! 3.0 syntax [#80](https://github.com/paritytech/cargo-contract/pull/80)
* Extract contract metadata to its own crate [#69](https://github.com/paritytech/cargo-contract/pull/69)
* Fix ManifestPath compiler errors [#73](https://github.com/paritytech/cargo-contract/pull/73)
* Upgrade cargo-xbuild and other dependencies [#71](https://github.com/paritytech/cargo-contract/pull/71)
* Update subxt and async-std dependencies [#66](https://github.com/paritytech/cargo-contract/pull/66)
* …
> Release v0.7.0

- src/cmd/build.rs
- src/cmd/metadata.rs
- src/crate_metadata.rs
- src/main.rs
- src/workspace/manifest.rs
Allows building contracts/generating metadata from a location outside the working directory.
Usage:
```
cargo run -- contract build --manifest-path ../ink/examples/erc2/Cargo.toml
cargo run -- contract generate-metadata --manifest-path ../ink/examples/erc20/Cargo.toml    
```
The `--manifest-path` flag is so named from the equivalent option in `cargo` which has the same effect.
> Specify optional --manifest-path for build and generate-metadata

- .gitlab-ci.yml
- Cargo.lock
- Cargo.toml
- README.md
- src/cmd/build.rs
> Use binaryen-rs as dep instead of requiring manual wasm-opt installation

- Cargo.lock
- Cargo.toml
- src/cmd/build.rs
The [`build-std`](https://doc.rust-lang.org/nightly/cargo/reference/unstable.html#build-std) feature of cargo now allows to specify the `panic-immediate-abort` feature. See: https://github.com/rust-osdev/cargo-xbuild#alternative-the-build-std-feature-of-cargo.
So we can use that (unstable) feature instead of depending on `xbuild`
Produces the same size wasm output as with `xbuild` e.g. flipper:
> Replace xbuild with cargo build-std

- README.md
- metadata/lib.rs
- src/cmd/build.rs
- src/cmd/metadata.rs
- src/main.rs
Closes #96 by implementing
* a new command `cargo contract build`, which results in a `target/metadata.json`, a `target/<name>.wasm`, and a `target/<name>.contract` (the .pack file mentioned in the issue).
* a new command `cargo contract check`, which just tries to build the contract without generating metadata or optimizing the Wasm.
* deprecates `cargo contract generate-metadata` for `cargo contract build` (which implicitly does this or via `--metadata-only` skips unnecessary operations not strictly needes for generating metadata).
> Implement new commands `build` and `check` + introduce bundles (.contract files)

- src/cmd/metadata.rs
Makes quite a difference.
`flipper.contract` with `serde_json::to_string_pretty()`: `7.0K`
`flipper.contract` with `serde_json::to_string()`: `6.1K`
> Do not prettify JSON for bundle

- src/workspace/manifest.rs
Fixes #106, and any other case where the `[lib] name` field does not match exactly with the contract package name.
This PR fixes this by using the package name when generating the dependency from the metadata package.
> Use package name instead of lib name for metadata dependency

- src/main.rs
You can provoke this by e.g. applying this patch to `ink/examples/dns/Cargo.toml`:
```
[lib]
-name = "dns"
+name = "d ns"
```
and then
```
cargo run -- contract build --manifest-path ../ink/examples/dns/Cargo.toml 
echo $?
```
After the merge we should move the `ink-ci-v0.8.0` tag ahead to this commit.
This is another reason why some of the stages in the ink! CI succeed even though `cargo-contract` fails.
> Exit with 1 on Err

- src/cmd/new.rs
During https://github.com/paritytech/ci_cd/issues/75 we ran into issues where this test always failed:
```
thread 'cmd::new::tests::rejects_hyphenated_name' panicked at 'assertion failed: `(left == right)`
left: `"Err(Contract names cannot contain hyphens\n\nStack backtrace:\n   0: anyhow::private::new_adhoc\n             at /ci-cache/cargo/registry/src/github.com-1ecc6299db9ec823/anyhow-1.0.33/src/lib.rs:610\n   1: cargo_contract::cmd::new::execute\n             at ./src/cmd/new.rs:31\n   2: cargo_contract::cmd::new::tests::rejects_hyphenated_name::{{closure}}\n             at ./src/cmd/new.rs:107\n   3: cargo_contract::util::tests::with_tmp_dir\n             at ./src/util.rs:101\n   4: cargo_contract::cmd::new::tests::rejects_hyphenated_name\n             at ./src/cmd/new.rs:106\n   5: …
```
> Check explicitly for error message

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- metadata/Cargo.toml
* Exit with 1 on Err [#109](https://github.com/paritytech/cargo-contract/pull/109)
* Use package name instead of lib name for metadata dependency [#107](https://github.com/paritytech/cargo-contract/pull/107)
* Do not prettify JSON for bundle [#105](https://github.com/paritytech/cargo-contract/pull/105)
* Make `source.hash` non-optional, remove metadata-only [#104](https://github.com/paritytech/cargo-contract/pull/104)
* Implement new commands `build` and `check` + introduce bundles (.contract files) [#97](https://github.com/paritytech/cargo-contract/pull/97)
* Replace xbuild with cargo build-std [#99](https://github.com/paritytech/cargo-contract/pull/99)
* Use binaryen-rs as dep instead of requiring manual wasm-opt installation [#95](https://github.com/paritytech/cargo-contract/pull/95)
* …
> Release v0.8.0

- .gitlab-ci.yml
Put the image name into a var so it can be changed by an upstream pipeline trigger.
Companion PR: https://github.com/paritytech/scripts/pull/238
> Nightly test new CI image

- src/cmd/build.rs
- src/cmd/metadata.rs
- src/cmd/mod.rs
- src/main.rs
- src/util.rs
I had it in the back of my head for a while now to have `main.rs` be just the dispatcher for `build` and `check` and have the logic reside in the appropriate modules. This was something that came up in a review a while ago.
There are some more minor refactorings in here, like consistent naming and moving a function to utilities.
Also a small fix is in here: for `check` the output of the steps in the progress (`[{}/{}]`) was one off.
> Refactorings for `build` and `check`

- Cargo.lock
- Cargo.toml
My PR https://github.com/paritytech/wasm-utils/pull/145 has been merged and a new release is out. Hence we can upgrade now.
> Upgrade: `pwasm-utils` ➜ 0.16.1, `parity-wasm` ➜ 0.42.1

- build.rs
- metadata/lib.rs
warning: length comparison to zero
--> build.rs:104:19
|
104 |         } else if name.as_os_str().len() != 0 {
|                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: using `!is_empty` is clearer and more explicit: `!name.as_os_str().is_empty()`
ok_or be replaeced ok_or_else. You do it, or I'll do it when I have time.
> fix clippy ==0 be replaced is_empty()

- src/workspace/mod.rs
warning: use of `expect` followed by a function call
--> src/workspace/mod.rs:55:18
|
55 |                   .expect(&format!(
|  __________________^
56 | |                     "Package '{}' is a member and should be in the packages list",
57 | |                     package_id
58 | |                 ));
| |__________________^ help: try this: `unwrap_or_else(|| panic!("Package '{}' is a member and should be in the packages list", package_id))`
|
= note: `#[warn(clippy::expect_fun_call)]` on by default
= help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#expect_fun_call
> feat expect warning

- Cargo.lock
- Cargo.toml
- templates/new/_Cargo.toml
Related: https://github.com/paritytech/ink/pull/663
> Update to scale-info 0.5 and codec 2.0

- src/cmd/build.rs
- src/cmd/metadata.rs
- src/cmd/new.rs
- src/main.rs
- src/util.rs
- src/workspace/manifest.rs
Closes #134.
Supersedes #133.
From the issue:
>[…] investigate whether we should print progress updates to stderr as I believe cargo does (needs confirming).
I investigated and the `cargo` behavior is that progress output is suppressed entirely for `--quiet`, but errors are still printed to `stderr`. This is the behavior which I implemented in this PR.
> Suppress output on `--quiet`

- Cargo.toml
- README.md
- build.rs
- src/cmd/build.rs
Closes #113.
Soo, this will get a bit hairy and I expect discussion in this PR.
Our initial idea of using our build script to dynamically enable the `binaryen-rs` dependency based on availability of the `wasm-opt` binary won't work:
>The build script is run (once) after the dependencies are built, so without time travel it can not add dependencies.
(from https://github.com/rust-lang/cargo/issues/5499)
What we could do instead is to install `cargo-contract` either with
* `cargo install --features wasm-opt-unavailable`, if we want to use the `binaryen-rs` dep.
* or via the usual `cargo install`, if the `wasm-opt` binary is available.
This is currently implemented by this PR ‒ if the feature `wasm-opt-unavailable` is enabled the `binaryen-rs` dep is built and used for optimization.
To …
> Use either `binaryen-rs` dep or `wasm-opt` binary

- Cargo.lock
- Cargo.toml
`cargo-contract` doesn't build with `--features=extrinsics`. This patch makes version bumps that fix the build.
It is mostly updating the lockfile, but also bumping the substrate-subxt crate in the local manifest.
> Updated deps to fix extrinsics build

- README.md
- src/cmd/build.rs
Closes https://github.com/paritytech/cargo-contract/issues/183.
> Fix `wasm-opt` regression

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- Implement Wasm validation for known issues/markers - [#171](https://github.com/paritytech/cargo-contract/pull/171)
- Use either `binaryen-rs` dep or `wasm-opt` binary - [#168](https://github.com/paritytech/cargo-contract/pull/168)
- Update to scale-info 0.5 and codec 2.0 - [#164](https://github.com/paritytech/cargo-contract/pull/164)
- Put build artifacts under `target/ink/` - [#122](https://github.com/paritytech/cargo-contract/pull/122)
- Fix `wasm-opt` regression - [#187](https://github.com/paritytech/cargo-contract/pull/187)
- Generate metadata explicitly for the contract which is build - [#174](https://github.com/paritytech/cargo-contract/pull/174)
- Fix bug with empty Wasm file when using system binaryen for optimization - …
> Release 0.9.0

- src/cmd/metadata.rs
- src/crate_metadata.rs
- src/util.rs
- src/workspace/manifest.rs
Closes https://github.com/paritytech/cargo-contract/issues/198 and https://github.com/paritytech/ink/issues/701.
My understanding is that the linker error was a result of conflicting build artifacts in the `target` directory. 
The root contract is build with the `ink-as-dependency` feature enabled for sub-contracts, whereas the sub-contracts are build without this flag. This results in the external function `__ink_generate_metadata` (which is only build when `ink-as-dependency` is disabled) not being available in the artifacts, but cargo still tries to reuse the artifacts. Hence the linker error.
I fixed it now by building sub-contracts into sub-folders of `target/ink/`. This way all artifacts are separate.
> Fix linker error when building complex contracts

- src/cmd/new.rs
> no periods in new contract names

- templates/new/_Cargo.toml
Closes https://github.com/paritytech/ink/issues/705.
We have a test for `cargo contract new`, but the test is currently not run in CI. I've created https://github.com/paritytech/cargo-contract/pull/180 to fix this. This PR here is a pre-requirement to make the test run in CI again though. So after we have merged this PR I can update the other one.
> Fix `cargo contract new` template build

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- no periods in new contract names - [#192](https://github.com/paritytech/cargo-contract/pull/192)
- Update `cargo contract new` template dependencies for `ink!` `rc3` - [#204](https://github.com/paritytech/cargo-contract/pull/204)
> Release 0.10.0

- Cargo.lock
- Cargo.toml
- src/crate_metadata.rs
- src/workspace/manifest.rs
- src/workspace/mod.rs
Also simplifies `ManifestPath` construction
> Upgrade cargo-metadata and fix usages

- src/cmd/new.rs
> Only allow new contract names beginning with an alphabetic character

- src/cmd/build.rs
- src/cmd/metadata.rs
- src/main.rs
- templates/new/lib.rs
> Adding "optimization-passes" option

- src/cmd/build.rs
- src/cmd/metadata.rs
- src/main.rs
Refactor triggered by discussion around https://github.com/paritytech/cargo-contract/pull/180/files#r591270056
- Refactor the build command in order to consolidate the logic around `BuildArtifacts` to a single place.
- No longer executes the build from within `metadata.rs`
- Replaces the `MetadataCommand` with free functions since it is no longer a top level command (this explains much of the diff in `metadata.rs`, but the code is mostly unchanged apart from the above mentioned change).
> Refactor build command

- README.md
- src/cmd/build.rs
- src/main.rs
- src/workspace/manifest.rs
Final piece for closing https://github.com/paritytech/cargo-contract/issues/169.
> Support `optimization-passes` in the release profile

- .gitlab-ci.yml
We should ensure that the project template always works. 
Having this as a CI stage ensures that the template will work with changes to the template, to dependencies, and with recent Rust versions.
The tests which we already have in the codebase execute functions in `cmd` directly. The CI stage on the other hand is a proper end-to-end test. Also the tests in the codebase don't run `cargo test`/`cargo check`/`cargo fmt`.
> Test new project template in CI

- src/cmd/build.rs
- src/main.rs
`master` currently fails because of the missing derive. Not sure why this wasn't catched in the CI run before the merge.
I also noticed that one of the tests which I added doesn't actually `manifest.write()`.
> Add missing derive

- src/cmd/build.rs
- src/workspace/manifest.rs
Closes https://github.com/paritytech/cargo-contract/issues/232.
CI currently fails because `master` fails (see https://github.com/paritytech/cargo-contract/pull/236 for the fix for that).
@Robbepop @ascjones Are you aware of any other dependencies of a contract which must be compatible with the ink! version of that dependency? `scale-info`?
> Detect version mismatches of `parity-scale-codec`

- templates/new/lib.rs
Just adding the ink prefix to the test attributes in the new template. Pretty minor, but if you don't notice and you copy the `#[test]` attribute for a more complex test, your test will break in a confusing way.
> ink::test attributes in new template

- src/cmd/build.rs
Possible improvement for the source of this error message here:
Suspect that the installed version of `wasm-opt` runs but doesn't produce the output file as expected.
I haven't reproduced it because my installation of `wasm-opt` is valid and produces a optimized file, however this is a useful check to make anyway, since we have no guarantees that `do_optimization` will write the optimized wasm fle.
> Check wasm optimized output file exists

- Cargo.lock
- Cargo.toml
- src/cmd/build.rs
The improved error message:
```
ERROR: wasm-opt not found!
We use this tool to optimize the size of your contract's Wasm binary.
wasm-opt is part of the binaryen package. You can find detailed
installation instructions on https://github.com/WebAssembly/binaryen#tools.
There are also ready-to-install packages for many platforms:
* Debian/Ubuntu: https://tracker.debian.org/pkg/binaryen
* Homebrew: https://formulae.brew.sh/formula/binaryen
* Arch Linux: https://archlinux.org/packages/community/x86_64/binaryen
* Windows: binary releases are available at https://github.com/WebAssembly/binaryen/releases
```
I'm aware that linking packages here can be seen as controversial, but due to the number of questions we get in public channels regarding this I think we should consider it.
> Detect compatible `wasm-opt` versions and improve error messages

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- Improve error output for `wasm-opt` interaction - [#244](https://github.com/paritytech/cargo-contract/pull/244)
- Check optimized Wasm output file exists - [#243](https://github.com/paritytech/cargo-contract/pull/243)
- Detect `wasm-opt` version compatibility and improve error messages - [#242](https://github.com/paritytech/cargo-contract/pull/242)
- Detect version mismatches of `parity-scale-codec` in contract and ink! dependency - [#237](https://github.com/paritytech/cargo-contract/pull/237)
- Support specifying `optimization-passes` in the release profile - [#231](https://github.com/paritytech/cargo-contract/pull/231)
- Support specifying `optimization-passes` on the CLI - [#216](https://github.com/paritytech/cargo-contract/pull/216)
- Use `ink::test` attribute in "new project" …
> Release 0.11.0

- README.md
- src/cmd/build.rs
Closes https://github.com/paritytech/cargo-contract/issues/247.
The issue was that binaryen includes more extensive version information in the `--version` output [only if built from source](https://github.com/WebAssembly/binaryen/blob/main/CMakeLists.txt#L20-L35). If installed via a package manager the version output can be more compact.
I've also escalated this into the ticket https://github.com/paritytech/ci_cd/issues/121, to install `binaryen` from a package manager in our CI.
> Fix `wasm-opt --version` parsing

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- Fix `wasm-opt --version` parsing - [#248](https://github.com/paritytech/cargo-contract/pull/248)
> Release 0.11.1

- Cargo.lock
- Cargo.toml
for https://github.com/paritytech/ink/pull/754
There are a bunch of outdated references that already existed (parity-scale-codec 1.3.6 for example), is there a reason for this?
> Bump scale codec version

- CHANGELOG.md
- Cargo.toml
- README.md
- src/cmd/build.rs
- src/main.rs
It caused only problems and complicated things.
I removed it from our CI as well: https://github.com/paritytech/scripts/pull/285. We now install `binaryen` as a system package in our docker image (this was not possible a couple weeks ago).
> Remove support for `binaryen-as-dependency`

- src/workspace/profile.rs
CI on `master` currently fails due to this:
https://gitlab.parity.io/parity/cargo-contract/-/jobs/894585
> Fix `clippy:wrong_self_convention`

- src/cmd/build.rs
- src/cmd/metadata.rs
- src/cmd/new.rs
- src/crate_metadata.rs
- src/util.rs
It's hunting season for https://github.com/paritytech/cargo-contract/issues/234 🏹!
I found it!
The issue was that we use
```
CARGO_TARGET_DIR: "/ci-cache/${CI_PROJECT_NAME}/targets/${CI_COMMIT_REF_NAME}/${CI_JOB_NAME}"
```
in our CI configuration. This made all tests build to the same `target` directory. Since we have a number of tests which build a contract called `new_project` this made our `tmp_dir`'s obsolete and resulted in overlapping contracts build to e.g. `/ci-cache/cargo-contract/targets/263/test/ink/new_project.contract`.
The way I fixed it now is by appending a hash of a contract's `manifest_path` to the `target_directory` (for tests this path contains the `tmp_dir` path). This results in the paths now being e.g. `/ci-cache/cargo-contract/targets/263/test/0xd82f746d702f63617267 …
> Fix flaky CI test

- CHANGELOG.md
- README.md
- src/main.rs
Is has been marked as deprecated since https://github.com/paritytech/cargo-contract/pull/97.
> Remove deprecated `generate-metadata` command

- .github/workflows/windows.yml
- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- src/cmd/build.rs
- src/workspace/manifest.rs
- src/workspace/mod.rs
Closes https://github.com/paritytech/cargo-contract/issues/36.
Took inspiration [from here](https://github.com/paritytech/libsecp256k1/blob/master/.github/workflows/rust.yml).
The Windows run currently takes ~9 minutes.
While implementing this, I found the bug which caused some people asking in our channels why they got this error when building a contract under Windows:
```
[3/5] Optimizing wasm file
ERROR: The workspace root package should be a workspace member
```
It was due to a comparison of a non-canonicalized path with a canonicalized one.
```
workspace_root (non-canonicalized): "D:\\a\\cargo-contract\\cargo-contract\\foobar"
package_path (canonicalized):       "\\\\?\\D:\\a\\cargo-contract\\cargo-contract\\foobar"
comparison: Some("D:\\a\\cargo-contract\\cargo-contract\\foobar") == …
```
> Add CI for Windows

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- Fixed `ERROR: The workspace root package should be a workspace member` when building a contract under Windows - [#261](https://github.com/paritytech/cargo-contract/pull/261)
- Remove support for `--binaryen-as-dependency` - [#251](https://github.com/paritytech/cargo-contract/pull/251)
- Remove support for the deprecated `cargo contract generate-metadata` command - [#265](https://github.com/paritytech/cargo-contract/pull/265)
- Remove pinned `funty` dependency from "new project" template - [#260](https://github.com/paritytech/cargo-contract/pull/260)
> Release 0.12.0

- CHANGELOG.md
- src/cmd/build.rs
This came up more often recently. Latest in https://github.com/paritytech/cargo-contract/issues/272, but also in the public channel.
> Suggest `binaryen` installation from GitHub on outdated version

- src/cmd/build.rs
- src/cmd/metadata.rs
- src/crate_metadata.rs
- src/workspace/manifest.rs
Closes https://github.com/paritytech/cargo-contract/issues/221.
> Always use `lib.name` for Wasm output file name

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- Suggest `binaryen` installation from GitHub release on outdated version - [#274](https://github.com/paritytech/cargo-contract/pull/274)
- Always use library targets name for contract artifacts - [#277](https://github.com/paritytech/cargo-contract/pull/277)<br class="Apple-interchange-newline">
> Release 0.12.1

- src/cmd/build.rs
- src/cmd/metadata.rs
- src/main.rs
- src/validate_wasm.rs
Fixes the broken `master` CI (see https://gitlab.parity.io/parity/cargo-contract/-/jobs/971882).
> Fix `clippy::needless_borrow`

- .gitlab-ci.yml
- README.md
- src/cmd/mod.rs
- src/cmd/test.rs
- src/main.rs
drafts `cargo contract test [FLAGS] [--manifest-path]`
in this first impl stdout is uncolored
let me know if you care much for the colors
> impl: test sub cmd with support for --manifest-path (#280)

- Cargo.lock
- Cargo.toml
- src/cmd/build.rs
- src/cmd/metadata.rs
In order to properly analyze a contract binary we need to keep the wasm name section alive so that we can see what is going on. Using the non post processed wasm file is of no use because we are interested in the fully optimized binary when doing an analysis. To that end I added a new `--keep-symbols` flag to the `build` command which prevents `wasm-opt` from removing the debug section.
I needed to make some other changes to make this work, too. Most notable I removed the call to `pwasm_utils::optimize` which unconditionally removes all custom sections. We don't need this anyways because `wasm-opt` does the same optimizations and more. It sufficed to remove all exports from the module (but `call` and `deploy`) to have the same result without `pwasm_utils::optimize`. I argue that having …
> Add `--keep-symbols` flag

- src/util.rs
One of the tests fails to pass on macOS. The reason is that the temporary pass used is a symlink and one side of the equality used path canonicalization while the other does not.
This PR fixes that by adding canonicalization to the test only `with_tmp_dir` function.
> Fix tests on macOS

- CHANGELOG.md
- src/cmd/build.rs
- src/main.rs
This PR changes the default optimization option passed to `wasm-opt` from `-O3` to ~~`-Os`~~`-Oz`.
This saves us around 0.2-0.3K according to [these rough benchmarks](https://github.com/paritytech/cargo-contract/issues/110#issuecomment-882844120).
~~The default wasn't set to `-Oz` as I saw no noticeable size improvements, and it just
takes more time to run. However, you could also argue that since contracts are in general
quite small the extra time for `-Oz` is negligible so we should enable it anyways.~~
~~While I could be convinced of this, I'm not sure what hardware other people build on, and
the negative impact the change to `-Oz` could have for them.~~
> Change default optimizations pass to focus on code size

- .rustfmt.toml
- CHANGELOG.md
- src/cmd/build.rs
- src/cmd/metadata.rs
- src/main.rs
Closes https://github.com/paritytech/cargo-contract/issues/284.
Kinda blocked until we have a release of ink! `3.0.0-rc4`, since the `ink_env/ink-debug` feature is newer than the currently released `3.0.0-rc3`. The tests are failing because they use the published ink! crates.
This PR adds a new CLI flag `--release`, which mirrors the behavior of `cargo` ‒ compiling the artifact in release mode is not done by default.
> Implement `BuildMode`

- Cargo.lock
- Cargo.toml
- metadata/Cargo.toml
- metadata/README.md
There were only dependency updates for that crate, some in minor version though, hence I would bump from the minor version here as well.
> Release `contract-metadata` v0.3.0

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
ink! rc4 has just been published, I would also release `cargo-contract` now, so that's in sync (especially for the `ink_debug!` stuff).
> Release 0.13.0

- scripts/pre_cache.sh
Closes: https://github.com/paritytech/ci_cd/issues/166
Let's try your suggestion @cmichi , but I'm pretty sure that the logic there is that it happens only if there's no such a cache dir on the host.
Last time I was revisiting a similar issue I came to the conclusion that this happens because cargo automatically removes some old caches.
> CI: force cache pre-population

- CHANGELOG.md
- templates/new/_Cargo.toml
By default, Cargo's dependency resolver leaks `std` features from `dev-dependencies` into
`no_std` builds. This results in confusing errors messages such as the one in
https://github.com/paritytech/ink/issues/889. 
To avoid issues like this we can use the new(ish) dependency resolver, which doesn't leak
features from `dev-dependencies` into the regular build. You can read more about it [here](https://doc.rust-lang.org/cargo/reference/resolver.html#feature-resolver-version-2).
> Use new dependency resolver for template contract

- src/cmd/build.rs
We should keep the panic messages for debug builds because they convey valuable information. Until `Result` based error handling is implemented that is even the only way of reacting to runtime errors (as opposed to programming errors for which panics are usually used).
> Do not strip out panic messages in debug builds

- CHANGELOG.md
- src/cmd/build.rs
- src/cmd/metadata.rs
- src/main.rs
Adds a new `--output-json` flag which will output `build` results in JSON instead of the
normal human readable format. This is useful for using `cargo-contract` in part of data
pipelines.
> Add option for JSON formatted output

- README.md
~~We can't use the default tag due to https://github.com/paritytech/ci_cd/issues/185.~~
Edit: Issue has been closed.
> Add docker usage examples

- src/cmd/build.rs
- src/cmd/metadata.rs
- src/main.rs
This PR adds a `--offline` flag which can be used to build contracts without network acces with `cargo contract build --offline`.
The motivation for providing this extra flag is to be able to compile Smart contracts in [ink! Playground](https://github.com/paritytech/ink-playground) within a safe docker environment without direct network access.
Ussing the `--offline` flag for `cargo contract build`, both, cargo build and also the generation of cargo contract metadata become possible without network connection, using cached dependencies only.
> Offline flag

- src/cmd/build.rs
`-Clinker-plugin-lto` reduced the size of my contract
From:
Original wasm size: 68.6K, Optimized: 31.9K
To:
Original wasm size: 67.2K, Optimized: 31.0K
> Use `-Clinker-plugin-lto` flag during Wasm build

- CHANGELOG.md
- Cargo.lock
- metadata/Cargo.toml
- metadata/byte_str.rs
- metadata/lib.rs
Extracted from #79. Would be required for any consumer to deserialize contract metadata into Rust types.
- Implement deserializing `cargo-contract` metadata
- Expose all fields as `pub` for decoded metadata.
> Deserialize metadata

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- metadata/Cargo.toml
- templates/new/_Cargo.toml
Follow-up to https://github.com/paritytech/ink/pull/1043.
[Preview here](https://github.com/paritytech/cargo-contract/blob/cmichi-release-0.16.0/CHANGELOG.md#0160---2021-11-25).
CI fails because we haven't published the new ink! rc yet.
> Release `cargo-contract` v0.16.0 and `metadata` v0.5.0

- src/cmd/build.rs
- src/workspace/manifest.rs
It should close https://github.com/paritytech/cargo-contract/issues/377.
I tested it with sub contracts from the `delegator` example in ink!.
> Added `workspace` section to override parent `workspace`

- .github/workflows/macos.yml
- .github/workflows/windows.yml
Adds a `macos` CI stage analogue to the Windows CI stage which we already have.
This is a follow-up to https://github.com/paritytech/ink/pull/1066.
> Add `macos` CI stage

- Cargo.lock
- Cargo.toml
- src/cmd/metadata.rs
Ran `cargo upgrade`, then `cargo update`. Updates `blake2` superseding #383, which required the `cargo update` because of some compilation errors.
> Bump dependencies, `cargo update` lockfile

- .github/workflows/macos.yml
- README.md
I've removed running the CI tests on MacOS, since those tests are not needed to be run under MacOS as well. We already test if the ink! examples can be built and tested with `cargo-contract`'s `master` in https://github.com/paritytech/ink/blob/master/.github/workflows/examples.yml.
> Do not run CI tests under MacOS

- .gitlab-ci.yml
I've added some `dylint` stuff to our CI docker image in https://github.com/paritytech/scripts/pull/382. The docker image can't be build currently though: https://gitlab.parity.io/parity/cargo-contract/-/jobs/1376793.
This is due to an ICE in the nightly version of the Rust compiler (https://github.com/rust-lang/rust/issues/93788). Since I need those `dylint` tools now-ish, I would like to temporarily allow the `clippy` stage to fail. We can revert this PR once the ICE is fixed.
Let's not go into a discussion of setting a fixed toolchain for our CI here.
> Revert me: Don't require `clippy` CI stage to succeed

- src/cmd/new.rs
> Fix `clippy::needless-borrow`

- Cargo.lock
- Cargo.toml
dependabot failed doing it in https://github.com/paritytech/cargo-contract/pull/453.
> Upgrade `nom-supreme` to `0.7.0`

- Cargo.lock
- Cargo.toml
- src/cmd/build.rs
- src/cmd/extrinsics/call.rs
- src/cmd/extrinsics/instantiate.rs
- src/cmd/extrinsics/mod.rs
- src/cmd/extrinsics/upload.rs
- src/cmd/test.rs
- src/main.rs
Seems to be the way to go, `substrate` has already done it. Also nice colours:
> Migrate from structopt to clap derive

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- metadata/Cargo.toml
- templates/new/_Cargo.toml
CI failure is expected due to unreleased crates.
> Release `cargo-contract` and `contract-metadata` 1.0

- CHANGELOG.md
- src/cmd/build.rs
Closes https://github.com/paritytech/cargo-contract/issues/449.
I named it `--skip--linting` instead of `--no--linting`.
> Added support of `--skip--linting` flag.

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- build.rs
Follow-up to https://github.com/paritytech/cargo-contract/issues/467, where we don't have an idea what causes it, but the next time someone runs into it we would have better error reporting.
> Improve error reporting during installation + Release `1.0.1`

- Cargo.toml
- build.rs
- ink_linting/.cargo/config.toml
Fixes #478
Apple Silicon wasn't defined in the `config.toml` of our linting project. And hence `dylint-link` wasn't used to produce the binary. I also added a hand full of other common architectures.
This won't fix the windows CI, though. I am not sure what is up with that.
> Fix linting support on Apple Silicon

- CHANGELOG.md
- src/cmd/extrinsics/call.rs
- src/cmd/extrinsics/instantiate.rs
After the migration from structopt to clap derive #457, the default for `Vec` opts is for `multiple_occurrences`, e.g. `--args arg1 --args arg2` whereas with structopt it was `multiple_values` e.g. `--args arg1 arg2`. This resulted in an error like `Found argument '2' which wasn't expected, or isn't valid in this context` when providing multiple values. 
As noted in [docs](https://docs.rs/clap/latest/clap/struct.Arg.html#method.multiple_values) for `multiple_values`, there are issues with its use so we should consider changing how contract arguments are specified.
However in the meantime this reverts to the original behaviour with `structopt` of accepting multiple values.
> Allow multiple args values for call and instantiate commands

- ink_linting/Cargo.lock
- ink_linting/_Cargo.toml
- ink_linting/rust-toolchain
- ink_linting/src/mapping_initialized.rs
I've upgraded analog to the examples in https://github.com/trailofbits/dylint/tree/master/examples.
I hope that this fixes some strange Windows CI problems in the ink! repo. I suspect a bug in that particular `rust-toolchain`.
> Upgrade to `dylint` release `2.0.0`

- src/cmd/build.rs
- src/main.rs
Fixes usage of `check-only` and removes need for `FromStr` impl.
> Use `ArgEnum` for `BuildArtifacts`

- Cargo.lock
- Cargo.toml
- build.rs
Supersedes #531.
https://github.com/rustsec/rustsec/pull/516 mentions that `current_platform` supersedes this functionality in the move from 2.0 to 3.0.
> Replace `platforms` with `current_platform`

- src/cmd/extrinsics/instantiate.rs
- src/cmd/extrinsics/transcode/encode.rs
- src/cmd/extrinsics/transcode/env_types.rs
- src/cmd/extrinsics/transcode/mod.rs
- src/cmd/extrinsics/transcode/transcoder.rs
Where a message or a constructor accepts a `Vec<AccountId>` as an argument e.g [`multisig`](https://github.com/paritytech/ink/blob/0897dea3a8995207fd3ce7ac623a36f0f3eb0672/examples/multisig/lib.rs#L283), the custom decoder should be used so that SS58 format. e.g.
```bash
contract instantiate \
--args 2 [5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY,5FHneW46xGXgs5mUiveU4sbTyGBzmstUspZC92UhjJM694ty] \
--suri //Alice \
--dry-run
```
> extrinsics: fix `Vec<AccountId>` args

- CHANGELOG.md
- src/cmd/extrinsics/mod.rs
Fixes the `SignedExtra` type to align with [`substrate-contracts-node`](https://github.com/paritytech/substrate-contracts-node/blob/main/runtime/src/lib.rs#L352) and the [parachain runtime](https://github.com/paritytech/cumulus/blob/master/polkadot-parachains/canvas-kusama/src/lib.rs#L79).
This PR changes it to `PolkadotExtrinsicParams` which is just an [alias](https://github.com/paritytech/subxt/blob/3d669f97c6d3adbb8297f458a1bb35e7ec5cc7ba/subxt/src/extrinsic/params.rs#L72) to `BaseExtrinsicParams<T, PlainTip>` which maps to the runtime `SignedExtra1 definition with `pallet_transaction_payment::ChargeTransactionPayment<Runtime>`
Fixes #515
> Fix extrinsic params for contract chains

- src/cmd/extrinsics/events.rs
- src/cmd/extrinsics/transcode/encode.rs
- src/cmd/extrinsics/transcode/env_types.rs
- src/cmd/extrinsics/transcode/mod.rs
- src/cmd/extrinsics/transcode/transcoder.rs
- src/main.rs
Following #547, instances of `H256`  in events are displayed as raw byte arrays. Like so (see Code::Stored::code_hash):
This PR introduces a customer decoder for `H256` instances which displays it as a hex encoded string instead:
In doing this I have split the custom type transcoders into separate encoders and decoders so that a type can have only one or both.
> Display `H256` instances in events as hex encoded string

- .gitlab-ci.yml
Enabling this `rusty-cachier` option will lead to creating "fresh" caches on each `master` pipeline run. Fresh caches don't include any leftovers from previous cache overlays.
> Don't spin up `rusty-cachier` caches on the main branch

- README.md
The Element channel is closed and the Discord channel is private for new users, so I replaced them with an invite to Stack Exchange. Not clear if the link will continue to work if the site name changes after private beta.
Also replaced the link to the frontend app and removed the chat badges.
> Fix outdated relevant links in readme

- CHANGELOG.md
- README.md
- src/cmd/decode.rs
- src/cmd/extrinsics/call.rs
- src/cmd/extrinsics/transcode/mod.rs
- src/main.rs
[Readme preview](https://github.com/paritytech/cargo-contract/blob/cmichi-update-readme-2022-05-19/README.md).
[Changelog preview](https://github.com/paritytech/cargo-contract/blob/cmichi-update-readme-2022-05-19/CHANGELOG.md).
> Improve readme and `decode` sub-command documentation

- Cargo.lock
Makes more sense to have a single PR bumping these than five
(see #579, #580, #581, #582, #583).
> Bump ink! dependencies to `v3.2`

- src/cmd/extrinsics/instantiate.rs
When calling `instantiate_with_code` more than once (with different `salt` values), since the code has already been uploaded on the first call, subsequent calls will not store the code and not raise the `CodeStored` event. 
Fixes #589.
> Fix `instantiate_with_code` with already uploaded code

- Cargo.lock
- Cargo.toml
Looks like `v0.14.3` was yanked, which is causing problems if you try
and install `cargo-contract` from Git.
> Bump `cargo_metadata` to `v0.15.0`

- Cargo.lock
- Cargo.toml
- templates/new/_Cargo.toml
- transcode/Cargo.toml
Increases minimum required version to 3.3 to ensure skipping semver incompatible version 3.2.
> Bump all ink dependencies to 3.3

- .gitlab-ci.yml
This lint is fixed in https://github.com/paritytech/ink/pull/1311, but it won't be pulled in until a new release of `ink!` since the new project template uses `ink!` from crates.io.
This is a temporary fix to make CI green and should be removed once there is a new `ink!` release.
> Temporarily disable `clippy::let-unit-value` lint for new project template

- .gitlab-ci.yml
* Use lightweight image for the `rusty-cachier-notify` job
* Skip all Git operations
* Run the job on the Kubernetes runner
> Speed up `rusty-cachier-notify` job

- .gitlab-ci.yml
The `paritytech/contracts-ci-linux:production` image defaults to a `nightly` toolchain, default `rusty-cachier` to it too.
> Default `rusty-cachier` to a `nightly` toolchain

- .github/workflows/windows.yml
The download step of binaryen for Windows apparently uses the wrong path within the archive.
> Fix CI: Wrong path of binaryen

- Cargo.lock
- ink_linting/Cargo.lock
- ink_linting/_Cargo.toml
Updates all the `ink_*` dependencies instead of just a couple (take that dependabot!).
Supersedes #684 and #685.
> Bump `ink_*` crates to `v3.3.1`

- Cargo.lock
- Cargo.toml
- build.rs
- ink_linting/rust-toolchain.toml
Fixes #649 :crossed_fingers: 
Copied workaround from dylint source: https://github.com/trailofbits/dylint/blob/f5cb5b765573526bb08255a6c905c363ce461243/internal/src/cargo.rs#L52
Also see https://github.com/rust-lang/rustup/issues/3036#issuecomment-1193568646 and https://github.com/rust-lang/rustup/issues/3050
> Fix windows dylint build

- .gitlab-ci.yml
- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- metadata/Cargo.toml
Notable PRs:
- Fix windows dylint build (#690)
- Dry run gas limit estimation [#484](https://github.com/paritytech/cargo-contract/pull/484)
- Bump `ink_*` crates to `v3.3.1` [#686](https://github.com/paritytech/cargo-contract/pull/686)
- Refactor out transcode as a separate library [#597](https://github.com/paritytech/cargo-contract/pull/597)
- Sync `metadata` version with `cargo-contract` [#611](https://github.com/paritytech/cargo-contract/pull/611)
- Adapt to new subxt API [#678](https://github.com/paritytech/cargo-contract/pull/678)
- Replace log/env_logger with tracing/tracing_subscriber [#689](https://github.com/paritytech/cargo-contract/pull/689)
- contract upload: emitting a warning instead of an error when the contract already existed is more user friendly …
> Release v1.5.0

- src/cmd/extrinsics/call.rs
- src/cmd/extrinsics/instantiate.rs
- src/cmd/extrinsics/mod.rs
- src/cmd/extrinsics/upload.rs
> Replace custom RPCs by `state_call`

- Cargo.lock
- Cargo.toml
- src/cmd/extrinsics/integration_tests.rs
- src/cmd/metadata.rs
- src/util.rs
Enables the `env_filter` feature of `tracing_subscriber`. Previously all messages above `INFO` were displayed even if `RUST_LOG` was not set:
Now:
Also enabled special init function for testing.
> Fix `tracing_subscriber` filtering

- .github/workflows/macos.yml
- .github/workflows/windows.yml
- .gitlab-ci.yml
- build.rs
- ink_linting/README.md
- ink_linting/rust-toolchain.toml
- src/util.rs
Instead of using a `nightly` toolchain we want to build contracts with a `stable` compiler. Since we use nightly features we need to pass the `RUSTC_BOOTSTRAP=1` env variable.
This PR does the following:
- Pass `RUSTC_BOOTSTRAP=1` when building contracts and the dylint driver
- Check that the user uses a stable compiler with a minimum version
- Remove the toolchain file from ink_dylint since we just build it with a stable compiler
- The UI tests in CI are still run against a fixed nightly version
- Fix the CI to use a stable compiler and other small stuff that broke
I don't like this brittle setup of packaging the dylint binary driver **at call**. I suggest we just patch the users manifest on the fly at runtime to contain this:
```toml
[workspace.metadata.dylint]
libraries = [
{ git = …
```
> Build contracts and dylint driver with stable

- tests/decode.rs
I was confused as to why my local toolchain kept getting overriden from `stable` to
`nightly` after a test run. Turns out its from this decode test.
> Remove `nightly` override from decode test

- src/main.rs
- src/util.rs
There have been a couple warnings which were introduced recently which only appear when
running `cargo test`. Since our CI runs with `cargo test --all-features` we didn't end up
seeing these.
> Fix `cargo test` warnings

- .gitlab-ci.yml
`cargo install` avoids pre-releases unless explicitly asked to install one.
> Explicitly install pre-relase

- src/cmd/build.rs
It looks like as part of #703 we added [a `--quiet` flag](https://github.com/paritytech/cargo-contract/pull/703/files#diff-46230eb6eb9a3792464a39b022f624c28ce91fed38482b30f47f483f7ef14967R344)
when running the linter. The `--output-json` flag also adds a `--quiet` flag resulting in
a failed run due to duplicate flags.
```
❮ RUSTC_BOOTSTRAP=1 cargo +stable contract build --output-json
error: The argument '--quiet' was provided more than once, but cannot be used multiple times
USAGE:
cargo dylint [OPTIONS] [NAMES]... [-- <ARGS>...]
For more information try --help
ERROR: `"/.../bin/cargo" "dylint" "--lib=ink_linting" "--quiet" "--quiet"` failed with exit code: Some(2)
```
~~I figured that we probably don't want to run the linting step when running with
`--output-json` anyways, and by …
> Don't use `--quiet` verbosity by default when running dylint

- src/cmd/metadata.rs
- src/main.rs
The solution simply bumps the number of steps in the build workflow.
The result for build with `all` flag:
```bash
cargo contract build --skip-linting --generate all
[1/6] Skip ink! linting rules
[2/6] Building cargo project
Updating crates.io index
Finished release [optimized] target(s) in 0.26s
[3/6] Post processing wasm file
[4/6] Optimizing wasm file
[5/6] Generating metadata
Updating crates.io index
Compiling metadata-gen v0.1.0 (/private/var/folders/4v/n3610fp154z5qxgdqf8nnpj80000gn/T/cargo-contract_dxoOs4/.ink/metadata_gen)
Finished release [optimized] target(s) in 0.79s
Running `target/ink/release/metadata-gen '' `
[6/6] Generating bundle
...
```
The result for build with `code-only` flag:
```bash
cargo contract build --skip-linting --generate code-only
[1/4] Skip ink! linting …
```
> Fix numbering of steps during `build`

- crates/cargo-contract/src/cmd/extrinsics/call.rs
- crates/cargo-contract/src/cmd/extrinsics/events.rs
- crates/cargo-contract/src/cmd/extrinsics/instantiate.rs
- crates/cargo-contract/src/cmd/extrinsics/mod.rs
- crates/cargo-contract/src/cmd/extrinsics/upload.rs
Some suggested refactorings for #722, feel free to accept or reject as you please. **NOT TESTED**, it compiles only.
- Proper handling and display of `subxt::Error` returned from `submit_extrinsic`, consistent with the dry run
- Removes some duplication in `instantiate` for displaying the extrinsic result.
- Moves `is_json` to a field in `Instantiate::exec`
- Moves unrelated fields from `events.rs` and moves them to their local and relevant extrinsics
- Removes `estaimated_gas` field, it is an input not an output.
> Suggested refactorings for PR #722 (`--output-json`)

- crates/cargo-contract/src/cmd/build/mod.rs
Fixes #732.
Skips the linting step if building with `--offline`. This is because `cargo dylint` requires network access to build the linting drivers.
> Skip linting if running building in --offline mode

- CHANGELOG.md
- Cargo.lock
- crates/cargo-contract/Cargo.toml
- crates/cargo-contract/src/workspace/manifest.rs
- crates/cargo-contract/templates/new/_Cargo.toml
- crates/metadata/Cargo.toml
- crates/transcode/Cargo.toml
This release supports compatibility with the [`v4.0.0-alpha.3`](https://github.com/paritytech/ink/releases/tag/v4.0.0-alpha.3)
release of `ink!`. It is *not* backwards compatible with older versions of `ink!`.
- `--output-json` support for `call`, `instantiate` and `upload` commands - [#722](https://github.com/paritytech/cargo-contract/pull/722)
- Skip linting if running building in --offline mode -  [#737](https://github.com/paritytech/cargo-contract/pull/737)
> Release `v2.0.0-alpha.3`

- CHANGELOG.md
- Cargo.lock
- crates/cargo-contract/Cargo.toml
- crates/cargo-contract/src/cmd/extrinsics/call.rs
- crates/cargo-contract/src/cmd/extrinsics/events.rs
- crates/cargo-contract/src/cmd/extrinsics/instantiate.rs
- crates/cargo-contract/src/cmd/extrinsics/mod.rs
- crates/cargo-contract/src/cmd/extrinsics/upload.rs
A bug in the `subxt` codegen meant that compact types as type parameters were not generated correctly. `storage_deposit_limit` is an `Option<Compact<u128>>` but was generated as a `Option<u128>` which resulted in incorrect encoding. https://github.com/paritytech/subxt/pull/651 fixes that issue and this PR uses the new `subxt` release and fixes the issue here.
Fixes https://github.com/paritytech/cargo-contract/issues/734
> Fix storage deposit limit encoding

- crates/cargo-contract/src/workspace/manifest.rs
Because contracts are built in a temp directory, dependencies with relative paths e.g. `ink = { path = "../../crates/ink", default-features = false }` are rewritten to their absolute paths.
However this currently only happens for dependencies in the `[dependencies]` section, and will not work for `[dev-dependencies]`.
This PR supports rewriting the `dev-dependencies` relative paths. 
Required for https://github.com/paritytech/ink/pull/1429
> Rewrite relative path for `dev-dependency`

- CHANGELOG.md
- Cargo.lock
- crates/cargo-contract/Cargo.toml
- crates/metadata/Cargo.toml
- crates/transcode/Cargo.toml
- Fix storage deposit limit encoding - [#751](https://github.com/paritytech/cargo-contract/pull/751)
- Rewrite relative path for `dev-dependency` - [#760](https://github.com/paritytech/cargo-contract/pull/760)
> Release `v2.0.0-alpha.4`

- CHANGELOG.md
- Cargo.lock
- README.md
- crates/cargo-contract/Cargo.toml
- crates/cargo-contract/src/main.rs
- crates/cargo-contract/src/wasm_opt.rs
Compile `wasm-opt` and call it as a library instead of as an external binary.
This PR has three patches that result in completely removing support for the `wasm-opt` CLI in favor of the crate. If desired, the third commit can be excluded, leaving support for both methods.
Documentation for the `wasm-opt` bindings:
- https://github.com/brson/wasm-opt-rs
- https://docs.rs/wasm-opt/latest/wasm_opt/
Things to be aware of about the `wasm-opt` crate:
- It depends on Rust 1.48+
- It depends on a c++17 compiler, and should emit a readable error if one is not available.
- The `wasm-opt-sys` crate takes a non-negligible amount of time to build (minutes on my underpowered laptop). It also does not do any incremental recompilation, so if the build is invalidated it will rebuild the C++ code from …
> Use integrated wasm-opt

- crates/cargo-contract/src/cmd/extrinsics/events.rs
> Log failure instead of failing when decoding an event

- Cargo.lock
- crates/cargo-contract/Cargo.toml
This minor release reduces the amount of binaryen source code packaged into the wasm-opt crates from 72 MB to 10 MB.
> Update wasm-opt to 0.110.1

- CHANGELOG.md
- README.md
- crates/cargo-contract/src/cmd/build/mod.rs
- crates/cargo-contract/src/cmd/build/tests.rs
- crates/cargo-contract/src/cmd/metadata.rs
- crates/cargo-contract/src/main.rs
- crates/cargo-contract/tests/decode.rs
Since the release of `ink 4.0`, lints are optional and currently there are no lints which are run from the `ink!` repo.
This PR replaces `--skip-linting` with the inverse `--lint` to make linting opt-in by default instead of opt out. That way if/when we do add lints to `ink` there will be no changes required here.
> Make linting opt in with `--lint`

- CHANGELOG.md
- Cargo.lock
- crates/cargo-contract/Cargo.toml
- crates/metadata/Cargo.toml
- crates/transcode/Cargo.toml
- Add Rust specific build info to metadata - [#680](https://github.com/paritytech/cargo-contract/pull/680)
- Removed requirement to install binaryen. The `wasm-opt` tool is now compiled into `cargo-contract` - [#766](https://github.com/paritytech/cargo-contract/pull/766).
- Make linting opt in with `--lint` - [#799](https://github.com/paritytech/cargo-contract/pull/799)
-  Log failure instead of failing when decoding an event - [#769](https://github.com/paritytech/cargo-contract/pull/769)
> Release `v2.0.0 alpha.5`

- Cargo.lock
- crates/cargo-contract/Cargo.toml
The only change here is that it contains a [backport of a Binaryen patch](https://github.com/brson/wasm-opt-rs/issues/105) that slightly reduces output size for modules that do not contain a 'memories' section.
> Upgrade wasm-opt to 0.110.2

- CHANGELOG.md
- Cargo.lock
- crates/cargo-contract/Cargo.toml
- crates/cargo-contract/src/cmd/extrinsics/balance.rs
- crates/cargo-contract/src/cmd/extrinsics/call.rs
- crates/cargo-contract/src/cmd/extrinsics/events.rs
- crates/cargo-contract/src/cmd/extrinsics/instantiate.rs
- crates/cargo-contract/src/cmd/extrinsics/mod.rs
- crates/cargo-contract/src/cmd/extrinsics/upload.rs
Closes #673 
Example of denomination of balances when running a call on substrate contracts node:
```
Event Balances ➜ Transfer
from: 5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY
to: 5FUdyfmrdbk1H5F1E4HnweiQjENqwAWnPxH2Mkty6LeK5at9
amount: 100.2nDOT
Event Balances ➜ Reserved
who: 5FUdyfmrdbk1H5F1E4HnweiQjENqwAWnPxH2Mkty6LeK5at9
amount: 100.2nDOT
Event Balances ➜ Deposit
who: 5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY
amount: 188.457902μDOT
Event TransactionPayment ➜ TransactionFeePaid
who: 5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY
actual_fee: 4.23927238nDOT
tip: 0DOT
```
Balances can also be inputed in a denominated format (i.e. `500MDOT` for 500 x 10^6 x 10^`<tokenDecimals>`DOT).
The token symbol must match the one specified in the running local chain. If the chain …
> denominated units for balances in events

- crates/cargo-contract/src/validate_wasm.rs
`seal` prefixes have been removed, need to check for the module name now.
See https://github.com/paritytech/ink/pull/1482#issuecomment-1309424077
> Update validation for renamed FFI functions

- crates/cargo-contract/src/cmd/build/mod.rs
`nightly` rust [adds](https://github.com/paritytech/cargo-contract/issues/832) some new WASM features which are out of WASM MVP and hence not supported by `pallet_contracts` . 
This change should catch\avoid such cases on the `cargo contract build` step.
> add `-C target-cpu=mvp` rust flag to `build` command

- CHANGELOG.md
- crates/cargo-contract/src/cmd/extrinsics/instantiate.rs
> Add output-json check for `instantiate` command

- Cargo.lock
- crates/transcode/Cargo.toml
- crates/transcode/src/transcoder.rs
- forgot to update transcode `ink!` dependencies in https://github.com/paritytech/cargo-contract/pull/828
- remove unused `env_logger` dependency
> transcode: update ink! deps to beta, remove env_logger

- crates/cargo-contract/src/cmd/build/mod.rs
- crates/cargo-contract/src/cmd/build/tests.rs
- crates/cargo-contract/src/validate_wasm.rs
Companion to https://github.com/paritytech/ink/pull/1522.
Imports from `__unstable__` modules now invalid. However I have added an escape hatch `--skip-wasm-validation` which skips this check in case the user wants to build an incompatible version of `ink!`.
> Remove `unstable` module check, add `--skip-wasm-validation`

- crates/build/templates/new/_Cargo.toml
Since https://github.com/paritytech/ink/pull/1357 we require a minimum version of `2.3`
> Bump minimum requirement of `scale-info` in template to `2.3`

- crates/build/src/lib.rs
- crates/build/src/util/mod.rs
@HCastano reported the [following](https://github.com/paritytech/ink/pull/1523#pullrequestreview-1201375457) error when using `cargo +nighlty test` for E2E tests using the new [`contract-build`](https://github.com/paritytech/ink/pull/1523) library. First of all the error is misleading and is an occurrence of https://github.com/paritytech/cargo-contract/issues/746.
The issue is that the `+nightly` gets inherited and the `assert_channel` check fails. This PR removes this check entirely and allows the underlying `cargo build` command to inherit whatever toolchain the user needs. It still does add `RUSTC_BOOTSTRAP` in case we are building with `stable`.
This should now be more in line with `cargo` philosophy and give more flexibility to contract authors with their toolchain management.
See …
> Remove rust toolchain channel check

- CHANGELOG.md
- Cargo.lock
- crates/build/Cargo.toml
- crates/cargo-contract/Cargo.toml
- crates/metadata/Cargo.toml
- crates/transcode/Cargo.toml
- Pass `--features` through to `cargo` - [#853](https://github.com/paritytech/cargo-contract/pull/853/files)
- Remove rust toolchain channel check - [#848](https://github.com/paritytech/cargo-contract/pull/848/files)
- Bump minimum requirement of `scale-info` in template to `2.3` - [#847](https://github.com/paritytech/cargo-contract/pull/847/files)
- Remove `unstable` module check, add `--skip-wasm-validation` - [#846](https://github.com/paritytech/cargo-contract/pull/846/files)
- Extract lib for invoking contract build - [#787](https://github.com/paritytech/cargo-contract/pull/787/files)
- Fixed having non-JSON output after calling `instantiate` with `--output-json` - [#839](https://github.com/paritytech/cargo-contract/pull/839/files)
- add `-C target-cpu=mvp` rust flag to build command …
> Release `v2.0.0-beta.1`

- Cargo.lock
- crates/build/Cargo.toml
This upgrades binaryen to version 111.
Binaryen (and wasm-opt) now enables the `SignExt` and `MutableGlobals` features by default, which are also enabled in the LLVM backend. In the future Binaryen will align its default feature selection with the LLVM backend.
This is _probably_ is ok for cargo-contract - I assume, but don't know, that the substrate wasm vm allows these two common features.
This also points to potential future optimizations by explicitly turning on more features that the substrate vm supports, but aren't being enabled in wasm-opt.
The [changelog](https://github.com/brson/wasm-opt-rs/blob/master/CHANGELOG.md) for 0.111.0.
I see that the cargo-contract current version is a beta. If a major release is impending, it might be prudent to delay merging this.
> Upgrade wasm-opt to 0.111.0

- crates/build/src/wasm_opt.rs
As @brson pointed out in https://github.com/paritytech/cargo-contract/pull/888, this upgrade brings new Wasm features enabled by default. @Robbepop says these are supported by `wasmi` but still need to be enabled in `pallet-contracts` (/cc @athei). 
Originally I intended just to revert to `wasm-opt` `0.110`, but noticed in the [`CHANGELOG`](https://github.com/brson/wasm-opt-rs/blob/master/CHANGELOG.md) that there is the option of `.mvp_features_only()`, which I have added as an alternative in this PR.
> Enable `wasm-opt` MVP features only

- crates/transcode/src/env_types.rs
- crates/transcode/src/transcoder.rs
They are already required to be `'static`, so this seems like a reasonable requirement. In practice, it seems only `AccountId` and `Hash` transcoders are inserted into this collection. Adding these two traits allows a `ContractMetadataTranscoder` to be shared between threads via an `Arc`.  This is very useful, especially given a `ContractMetadataTranscoder` is not even `Clone`, which makes it unwieldy to load the metadata once and use it around the program.
> Require env_type transcoders to be Send + Sync

- CHANGELOG.md
- Cargo.lock
- crates/build/Cargo.toml
- crates/cargo-contract/Cargo.toml
- crates/metadata/Cargo.toml
- crates/transcode/Cargo.toml
- Upgrade wasm-opt to 0.111.0 [#888](https://github.com/paritytech/cargo-contract/pull/888)
- Enable `wasm-opt` MVP features only [#891](https://github.com/paritytech/cargo-contract/pull/891)
- Require env_type transcoders to be Send + Sync [#879](https://github.com/paritytech/cargo-contract/pull/879)
- Add determinism arg to upload TX [#870](https://github.com/paritytech/cargo-contract/pull/870)
> Release `v2.0.0-beta.2`

- .github/dependabot.yml
Substrate deps should all be updated as a group, and manually. See[ PR spam ](https://github.com/paritytech/cargo-contract/pulls?q=is%3Apr+sp-).
See also https://github.com/paritytech/ink/pull/1588
> dependabot: ignore substrate deps

- .github/dependabot.yml
- Cargo.lock
- crates/build/src/crate_metadata.rs
- crates/build/src/lib.rs
- crates/build/src/metadata.rs
- crates/build/src/tests.rs
- crates/cargo-contract/Cargo.toml
- crates/cargo-contract/src/cmd/extrinsics/call.rs
- crates/cargo-contract/src/cmd/extrinsics/events.rs
- crates/cargo-contract/src/cmd/extrinsics/instantiate.rs
- crates/cargo-contract/src/cmd/extrinsics/mod.rs
- crates/cargo-contract/src/cmd/extrinsics/upload.rs
- crates/metadata/src/lib.rs
- crates/transcode/src/lib.rs
- docs/extrinsics.md
Extrinsic commands need to locate contract artifacts: for `upload` we require the contract Wasm and for `instantiate` and `call` the contract metadata. Currently this is designed to be similar to other `cargo` commands: providing a `--manifest-path` argument to point to the `Cargo.toml` of the contract project, if not present assuming the working directory is the project root. From there it can locate the artifacts in the `./target/ink/` directory. This is good for a development workflow from inside a project dir like:
`cargo contract build --release` 
`cargo contract upload --suri //Alice`
`cargo contract instantiate ...` 
Or from a different directory relative to the contract project directory:
`cargo contract build --manifest-path ../my-contract/Cargo.toml --release` 
`cargo contract …
> Extrinsics: allow specifying contract artifact directly 

- CHANGELOG.md
- Cargo.lock
- crates/build/Cargo.toml
- crates/cargo-contract/Cargo.toml
- crates/metadata/Cargo.toml
- crates/transcode/Cargo.toml
First release candidate for compatibility with [`ink! 4.0-rc`](https://github.com/paritytech/ink/pull/1590).
-  Extrinsics: allow specifying contract artifact directly [#893](https://github.com/paritytech/cargo-contract/pull/893)
> Release `v2.0.0-rc`

- src/cmd/build.rs
cargo-contract-1.5.1 still produces sign-ext instructions which aren't allowed by the contract runtime.
Let's fix it.
> wasm-opt with --mvp-features

- crates/cargo-contract/src/cmd/extrinsics/events.rs
- crates/cargo-contract/src/cmd/extrinsics/instantiate.rs
- crates/cargo-contract/src/cmd/extrinsics/upload.rs
Just a few small UI fixes:
Instantate: display Contract Account *after* the events so you don't have to scroll up:
Match "Events" header colour with other properties
Upload: Display code hash with hex
> Misc extrinsics display improvements

- crates/cargo-contract/src/cmd/extrinsics/call.rs
- crates/transcode/src/decode.rs
- crates/transcode/src/lib.rs
As reported by @lean-apple, there was a bug decoding a `LangError`:
```
cargo contract call -m switch --dry-run --suri //Alice  --contract $CONTRACT
ERROR: Error decoding type 6: Result
Caused by:
0: Error decoding type 8: ink_primitives::LangError
1: No variant found with discriminant 1
```
This is because we were ignoring the explicitly assigned discriminant:
```rust
pub enum LangError {
/// Failed to read execution input for the dispatchable.
CouldNotReadInput = 1u32,
}
```
and instead using the implicit discriminant to decode.
The issue now is that the result is possibly not very useful to the user:
Perhaps we should consider explicitly decoding the `LangError`?
> Fix decoding of `LangError`

- crates/build/src/crate_metadata.rs
- crates/cargo-contract/src/cmd/extrinsics/error.rs
- crates/cargo-contract/src/main.rs
Error information was missing the error chain, and only displaying the `context` message:
This PR use the `Debug` impl to display the error chain with the cause:
> Display the causes of an error

- README.md
- crates/cargo-contract/src/cmd/test.rs
New release of `cargo-contract` and `ink!` no longer require nightly toolchain for compiling smart contracts. Therefore, we remove it from docs.
> Remove `+nightly` from docs and READMEs

- CHANGELOG.md
- crates/build/src/workspace/mod.rs
Closes https://github.com/paritytech/cargo-contract/issues/926 and https://github.com/paritytech/cargo-contract/issues/938.
Copies the `Cargo.lock` to the tmp dir.
Before: 
After:
> Respect the lockfile

- CHANGELOG.md
- crates/build/src/crate_metadata.rs
- crates/build/src/lib.rs
- crates/build/src/metadata.rs
- crates/cargo-contract/src/cmd/extrinsics/mod.rs
- crates/transcode/src/lib.rs
- docs/extrinsics.md
> Rename `metadata.json` to `{contract_name}.json`

- crates/cargo-contract/src/cmd/extrinsics/call.rs
Regression introduced in #722 where it uses the `Debug` output for the returned dry-run value, instead of the `Display`. See before and after:
> Pretty-print call dry-run return data

- crates/transcode/src/lib.rs
Currently if you forget to supply `--args` to an instantiate/call, it will fail with a trap because of invalid input. e.g calling a constructor which has args but forgetting to add `--args`:
```
contract contract instantiate --suri //Alice
```
This PR adds a simple check which validates the number of args supplied is equal to the expected number of arguments to the ink! constructor or message.
> Error if mismatching # of args for instantiate/call

- Cargo.lock
- crates/cargo-contract/Cargo.toml
- crates/transcode/Cargo.toml
The latest subxt release https://github.com/paritytech/subxt/pull/824 updates to the latest substrate dependencies from `crates.io`
> Update `subxt` and substrate dependencies

- crates/build/templates/new/_Cargo.toml
- crates/build/templates/new/lib.rs
Looks like we forgot to do this in #970.
Not a huge deal since `cargo` will still pull in ink! 4.0, but we'll
probably want to issue a patch release soon in order to not confuse
users.
> Bump template to ink! 4.0

- crates/build/templates/generate-metadata/_Cargo.toml
Fixes #909.
Currently a contract is required to have `std` set as the default feature e.g. `[features] default = ["std"]`. Otherwise the metadata generation will fail with `undefined reference to __ink_generate_metadata'`, because that method is only generated with `std` enabled.
This PR explicitly imports the contract as a lib with `std` enabled, so it should now work with or without `default = ["std"]` in the contract's `Cargo.toml`
> Explicitly enable `std` feature for metadata generation

- CHANGELOG.md
- Cargo.lock
- crates/build/Cargo.toml
- crates/build/templates/new/_Cargo.toml
- crates/cargo-contract/Cargo.toml
- crates/metadata/Cargo.toml
- crates/transcode/Cargo.toml
- Explicitly enable `std` feature for metadata generation [#977](https://github.com/paritytech/cargo-contract/pull/977)
- Return artifact paths when contracts unchanged [#992](https://github.com/paritytech/cargo-contract/pull/992)
- Minimum requirements of `ink!` dependencies all updated to `4.0.1`
> Release `v2.0.2`

- CHANGELOG.md
- crates/cargo-contract/tests/decode.rs
- crates/transcode/src/lib.rs
- crates/transcode/src/util.rs
Closes #980 
The hex bytes are consumed for decoding values of arguments on demand. If there is not enough data to fill the buffer, the error is already thrown. Previously, spare bytes were just ignored. Since this PR, an error will be thrown if input buffer contains spare bytes.
Here is the small demo demonstrating that extra bytes in buffer do not affect decoding of value.
```rust
//boolean is 1 byte long
let value = true;
let encoded: Vec<u8> = vec![1, 12, 3];
let mut encoded: &[u8] = encoded.as_ref();
let decoded: bool = bool::decode::<&[u8]>(&mut encoded).unwrap();
// is true
assert_eq!(decoded, value);
//prints [12, 3]
println!("{encoded:?}")
```
> Limit input length for `decode` command

- CHANGELOG.md
- crates/build/src/args.rs
- crates/build/src/lib.rs
- crates/build/src/metadata.rs
- crates/build/src/workspace/manifest.rs
- crates/build/src/workspace/metadata.rs
- crates/build/templates/generate-metadata/_Cargo.toml
Fixes #1004.
- copies features from the contract package to the metadata-gen package manifest
- passes the features to the invoking of the generated metadata package
- fixes feature CLI args to be either comma separated or quoted space separated as per cargo: https://doc.rust-lang.org/cargo/reference/features.html#command-line-feature-options
> Pass contract features to metadata gen package

- Cargo.lock
- crates/build/Cargo.toml
Just keeping the crate up to date.
There don't appear to be significant changes in binaryen 112:
https://github.com/WebAssembly/binaryen/blob/main/CHANGELOG.md#v112
> Upgrade wasm-opt to 0.112.0

- CHANGELOG.md
- Cargo.lock
- crates/transcode/Cargo.toml
- crates/transcode/src/account_id.rs
- crates/transcode/src/env_types.rs
- crates/transcode/src/lib.rs
- crates/transcode/src/transcoder.rs
Removes the substrate dependencies from `contract-transcode`.
We copy the `AccountId32` type from `subxt`: https://github.com/paritytech/subxt/blob/ce0a82e3227efb0eae131f025da5f839d9623e15/subxt/src/utils/account_id.rs, with a few modifications so that it can work in place of `sp_core::crypto::AccountId32`
> Custom `AccountId32` impl, remove substrate deps

- CHANGELOG.md
- Cargo.lock
- crates/build/Cargo.toml
- crates/cargo-contract/Cargo.toml
- crates/metadata/Cargo.toml
- crates/transcode/Cargo.toml
- Dry-run `instantiate`, `call` and `upload` commands by default - [#999](https://github.com/paritytech/cargo-contract/pull/999)
- Add `cargo contract encode` command - [#998](https://github.com/paritytech/cargo-contract/pull/998)
- Limit input length for `decode` command - [#982](https://github.com/paritytech/cargo-contract/pull/982)
- Pass contract features to metadata gen package - [#1005](https://github.com/paritytech/cargo-contract/pull/1005)
- Custom AccountId32 impl, remove substrate deps - [#1010](https://github.com/paritytech/cargo-contract/pull/1010)
- Fixes issue with with incompatible `wasmtime` versions when dependant project has old substrate dependencies.
> `2.1.0` Release

- .github/workflows/ci.yml
- crates/transcode/Cargo.toml
Currently the CI only runs workspace level `build` and `test` commands. However it is possible that these will succeed but when building an individual crate it will fail. e.g the CI for https://github.com/paritytech/cargo-contract/pull/1010 succeeded, but when it came to releasing it, it didn't work because of [missing features](https://github.com/paritytech/cargo-contract/pull/1016/commits/d89ca994b84f4b519bca1a11b6c3b5fec220b603).
My guess is that there is another crate which depends on `primitive-types` at the workspace level, which pulls in the required features via feature unification.
This PR iterates over the crates in the `crates` dir and runs `check` on each one. When performing a release on an individual crate, `cargo publish` will run `cargo check` before publishing, so we want …
> Add CI check for all individual crates

- .github/workflows/ci.yml
Dependabot :robot: PRs [only have read permissions](https://github.blog/changelog/2021-02-19-github-actions-workflows-triggered-by-dependabot-prs-will-run-with-read-only-permissions/), so dependabot PRs auto merged to `master` fail with ["Resource not accessible by integration"](https://github.com/actions-rs/clippy-check/issues/2).
This PR implements this [workaround](https://github.com/actions-rs/clippy-check/issues/2#issuecomment-807878478) which runs clippy "manually" when the permissions are not present.
This is safer than just giving `write` permissions by default to `GITHUB_TOKEN`
> Manual clippy run for dependabot PRs :t-rex:

- .github/workflows/ci.yml
- crates/cargo-contract/src/cmd/extrinsics/integration_tests.rs
Since https://github.com/paritytech/cargo-contract/pull/928, the tests have not been running at all on CI, due to a trailing ampersand on the `run` command (or at least executing async and not reporting back).
This PR makes the tests run again, and fixes the broken  `build_upload_instantiate_call` test.
It also combines the download and install `substrate-contracts-node` into a single step.
> Fix integration tests and CI tests :t-rex:

- Cargo.lock
- crates/build/templates/new/_Cargo.toml
- crates/transcode/Cargo.toml
- crates/transcode/src/decode.rs
- crates/transcode/src/encode.rs
- crates/transcode/src/env_types.rs
- crates/transcode/src/lib.rs
- crates/transcode/src/transcoder.rs
Accessors are deprecated and fields are made public, see https://github.com/paritytech/scale-info/pull/176
> Upgrade `scale-info` to `2.5`

- Cargo.lock
- crates/cargo-contract/Cargo.toml
- crates/cargo-contract/src/cmd/extrinsics/call.rs
- crates/cargo-contract/src/cmd/extrinsics/error.rs
- crates/cargo-contract/src/cmd/extrinsics/events.rs
- crates/cargo-contract/src/cmd/extrinsics/instantiate.rs
- crates/cargo-contract/src/cmd/info.rs
- crates/cargo-contract/src/cmd/runtime_api/mod.rs
Updating to use latest breaking changes from `0.28` see https://github.com/paritytech/subxt/blob/master/CHANGELOG.md
> Upgrade `subxt` to `0.28`

- Cargo.lock
- crates/build/src/lib.rs
- crates/build/src/metadata.rs
- crates/build/src/workspace/manifest.rs
- crates/build/src/workspace/mod.rs
Previously the whole workspace was copied to the temp dir. However we were only ever modifying and utilizing the target contracts manifest. This was causing unnecessary rebuilds of workspace contracts as experienced here: https://github.com/paritytech/ink/issues/1734.
> Only copy and rewrite target contract manifest

- Cargo.lock
- crates/build/src/tests.rs
- crates/build/src/workspace/manifest.rs
Currently contract projects with a build file fail to compile.
This PR fixes this by rewriting the path of the specified `build` file in the temp manifest.
Fixes #1060.
> Rewrites build file path in manifest

- CHANGELOG.md
- Cargo.lock
- crates/build/Cargo.toml
- crates/cargo-contract/Cargo.toml
- crates/metadata/Cargo.toml
- crates/transcode/Cargo.toml
- Add `info` command - [#993](https://github.com/paritytech/cargo-contract/pull/993)
- Add `--output-json` flag for `info` command - [#1007](https://github.com/paritytech/cargo-contract/pull/1007)
- Minimum requirements of `ink!` dependencies all updated to `4.2.0` - [#1084](https://github.com/paritytech/cargo-contract/pull/1084)
- Upgrade `subxt` to `0.28` [#1039](https://github.com/paritytech/cargo-contract/pull/1039)
- Upgrade `scale-info` to `2.5` [#1057](https://github.com/paritytech/cargo-contract/pull/1057)
- Rewrites build file path in manifest [#1077](https://github.com/paritytech/cargo-contract/pull/1077)
- Only copy and rewrite target contract manifest [#1079](https://github.com/paritytech/cargo-contract/pull/1079)
> Release `v2.2.0`

- Cargo.lock
- crates/build/Cargo.toml
- crates/cargo-contract/Cargo.toml
- crates/transcode/Cargo.toml
This reverts commit 0420cb828c131e68b385e5291327270ec75aa75c.
Unfortunately, tracing 0.1.38 has yanked which blocks people install the crate, could you make a release after this revert PR merged?
About the yank: https://github.com/tokio-rs/tracing/issues/2578
> Revert "Bump tracing from 0.1.37 to 0.1.38"

- Cargo.lock
- crates/build/Cargo.toml
- crates/build/src/lib.rs
- crates/build/src/metadata.rs
- crates/build/src/util/mod.rs
Since https://github.com/paritytech/cargo-contract/pull/1076, `no_main` is now required. This PR adds a suggestion in case of the error `error[E0601]: `main` function not found in crate...
This is the result:
Note that the suggestion must appear *before* the compiler error because we can't know for sure how many lines the error message will encompass, so we just print it first.
Introduces [duct](https://docs.rs/duct/latest/duct/) which allows for easily building command expressions and working with capturing the `stdout` and `stderr`.
An earlier iteration was using `BufReader::lines` to read the captured `stderr` and check for the error code for the missing main function. However this came with the downside of the familiar progress bar (see below) not being displayed.
I have been able to …
> Suggest adding `no_main` for `error[E0601]`

- CHANGELOG.md
- Cargo.lock
- crates/build/Cargo.toml
- crates/cargo-contract/Cargo.toml
- crates/metadata/Cargo.toml
- crates/transcode/Cargo.toml
- Experimental support for RISC-V contracts - [#1076](https://github.com/paritytech/cargo-contract/pull/1076)
- Contracts are build as `bin` crate now (we used `cdylib` before) - [#1076](https://github.com/paritytech/cargo-contract/pull/1076)
- BREAKING CHANGE: Make sure that your contract is `no_main` by having this on top of your contract:
- `#![cfg_attr(not(feature = "std"), no_std, no_main)]`
- This will be detected and suggested for `error[E0601]`  [#1113](https://github.com/paritytech/cargo-contract/pull/1113)
- Update contracts node metadata (#1105)
- Compatible with `substrate-contracts-node 0.25.0-a2b09462c7c`
- Fix original Wasm artifact path [#1116](https://github.com/paritytech/cargo-contract/pull/1116)
> Release `v3.0.0`

- CHANGELOG.md
- crates/build/Cargo.toml
- crates/cargo-contract/Cargo.toml
- crates/metadata/Cargo.toml
- crates/transcode/Cargo.toml
- `[contract-build]` flush the remaining buffered bytes [1118](https://github.com/paritytech/cargo-contract/pull/1118)
> Release `v3.0.1`

- crates/cargo-contract/src/cmd/info.rs
Change in the function basic_display_format_contract_info() to make the command `cargo contract info` use the same output format with other subcommands.
Fix of the Issue: https://github.com/paritytech/cargo-contract/issues/1112
Output:
> Make output format of cargo contract info consistent with other subcommands

- crates/cargo-contract/src/cmd/extrinsics/instantiate.rs
Modify the output in `cargo contract instantiate ` to show the gas consumed estimated when dry-run.
Fix the issue https://github.com/paritytech/cargo-contract/issues/1021
Output:
> Show Gas consumption by default for dry-runs

- crates/build/README.md
- crates/build/src/lib.rs
- crates/build/src/tests.rs
- crates/cargo-contract/src/cmd/build.rs
This PR adds and command line argument `--max-memory-pages` to `cargo contract build`.
Contracts on Phala Networks are allowed to use up to 4MB of memory. `cargo-contract` did enforce the wasm to set max pages to 16. That would cause a build error when our contracts use larger memory:
```
[3/5] Optimizing wasm file
[wasm-validator error in module] unexpected true: memory max >= initial, on 
memory
ERROR: Failed to validate wasm: error validating input
```
> Configurable max memory pages

- .github/workflows/ci.yml
Fixes CI jobs while https://github.com/paritytech/cargo-contract/issues/1139 is unnresolved
> :t-rex: pin jobs which build contracts to Rust `1.69`

- Cargo.lock
- crates/transcode/Cargo.toml
- crates/transcode/src/lib.rs
Suggest a valid message or constructor name when the user misspell it. 
If there are no close match, it will display the full list of available messages / constructors. 
This can be helpful when messages are namespaced and the user input it with the correct case
> Suggest valid message or constructor name, when misspelled

- crates/build/src/util/mod.rs
After this fix it is possible to run `dylint` with the linting library.
For example, to run the linter on the flipper contract we can use the following in the `ink` directory:
```
cd integration-tests/flipper/
DYLINT_LIBRARY_PATH="$(realpath ../../linting/target/debug)" cargo contract build --lint
```
It works, and we can test new lints using this.
Closes #1166
> fix(build): An error when running with `--lint`

- Cargo.lock
- crates/build/Cargo.toml
Just keeping wasm-opt updated.
There isn't much to be aware of in the binaryen 113 release notes:
https://github.com/WebAssembly/binaryen/blob/main/CHANGELOG.md#v113
wasm-opt has a minimum rust version of 1.48,
but wasm-opt's cxx dependency has recently changed their minimum rust version to 1.60. it should still be possible to resolve a crate graph that is 1.48 compatible, and I think this lockfile is, but if the cxx dependency in the lockfile is ever re-resolved cargo will probably pick a cxx that is not 1.48 compatible.
> Upgrade wasm-opt to 0.113

- CHANGELOG.md
- crates/build/src/lib.rs
- crates/build/src/metadata.rs
- crates/build/src/util/mod.rs
- crates/cargo-contract/src/cmd/build.rs
Extracted from https://github.com/paritytech/cargo-contract/pull/1210.
Adding as standalone PR to ensure there is an entry in the changelog for it.
Currently the verbose progress output goes to `stdout`, it should go to `stderr` as `cargo` does, which allows displaying of progress to the user and still be able to pipe `stdout` to a file or another program, as is required for `--output-json`
> Display build progress with `--output-json`, print to `stderr`

- Cargo.lock
- crates/build/Cargo.toml
- crates/build/src/docker.rs
The current progress display for pulling images jumps around because there are progress updates for the different layers. 
This PR uses the `CreateImageResult::progress` which shows the "native" docker progress, and moves the cursor to the relevant line which displays the progress for that layer.
> Display status of pulling docker image

- .github/workflows/ci.yml
- Cargo.lock
- build-image/README.md
- crates/cargo-contract/Cargo.toml
- crates/extrinsics/Cargo.toml
- crates/extrinsics/src/call.rs
- crates/extrinsics/src/instantiate.rs
- crates/extrinsics/src/lib.rs
- crates/extrinsics/src/remove.rs
- crates/extrinsics/src/upload.rs
https://github.com/paritytech/subxt/pull/1089
- Removes the `--password` option for signing extrinsics, the password must be part of the `--suri` e.g. `//Alice///PASSWORD`
- CI uses `stable` instead of `1.69`, this is required because `once_cell` is stablized now, and the issue with `sign_ext` is already fixed here.
> Update `subxt` to `0.30.1` with new `subxt-signer` crate

- CHANGELOG.md
- README.md
- build-image/Dockerfile
- crates/build/Cargo.toml
- crates/cargo-contract/Cargo.toml
- crates/extrinsics/Cargo.toml
- crates/metadata/Cargo.toml
- crates/transcode/Cargo.toml
**Notable changes:**
- Verifiable builds inside a docker container - [#1148](https://github.com/paritytech/cargo-contract/pull/1148)
- Extrinsics extracted to separate crate - [#1181](https://github.com/paritytech/cargo-contract/pull/1181)
- Fix building contracts with Rust >= 1.70: enable `sign_ext` Wasm opcode - [#1189](https://github.com/paritytech/cargo-contract/pull/1189)
- Standardised verifiable builds - [#1148](https://github.com/paritytech/cargo-contract/pull/1148)
- Enable Wasm sign_ext [#1189](https://github.com/paritytech/cargo-contract/pull/1189)
- Expose extrinsics operations as a library - [#1181](https://github.com/paritytech/cargo-contract/pull/1181)
- Suggest valid message or constructor name, when misspelled - [#1162](https://github.com/paritytech/cargo-contract/pull/116 …
> Release `v3.1.0`

- crates/extrinsics/Cargo.toml
The `subxt-signer` crate utilizes `OnceLock` which was only [stabilized](https://blog.rust-lang.org/2023/06/01/Rust-1.70.0.html#oncecell-and-oncelock) in `1.70`.
I have update the MSRV in subxt see https://github.com/paritytech/subxt/pull/1097. But we should do it here too so we can get a release out in the meantime to prevent issues such as https://github.com/paritytech/cargo-contract/issues/1240.
> `[extrinsics]` set minimum supported `rust-version` to `1.70`

- Cargo.lock
- crates/build/Cargo.toml
Just keeping wasm-opt updated.
There isn't much to be aware of in the binaryen 114 release notes:
https://github.com/WebAssembly/binaryen/blob/main/CHANGELOG.md#v114
> Update wasm-opt to 0.114

- .github/workflows/release-image.yml
- CHANGELOG.md
Follow-up for #1148
Adds a workflow that automatically pushes an image to the docker hub when:
- A new commit is pushed a master (in this case the `master` tag gets updated)
- A new release is published | prereleaed | edited (the new tag under the corresponding tag name gets published or updated)
> add build image release workflow

- Cargo.lock
- crates/cargo-contract/Cargo.toml
- crates/extrinsics/Cargo.toml
Supersedes https://github.com/paritytech/cargo-contract/pull/1257 and https://github.com/paritytech/cargo-contract/pull/1256
> Update `subxt` to `0.31.0`

- crates/build/src/lib.rs
- crates/build/src/wasm_opt.rs
Fixes #1239.
As suggested here: https://github.com/paritytech/cargo-contract/issues/1239#issuecomment-1673810089, this will allow a newer toolchain > `1.69` to be used to deploy to older versions of `pallet-contracts` which do not yet support `signext`.
It does so by adding an extra `wasm-opt` pass which "lowers" any `signext` instructions to mvp only features.
Tested that a contract built with Rust >= `1.70` can be uploaded to a node which does not support `signext`.
If it does work we can then consider either backporting this to a `3.2.0` release, or just going ahead and doing a `4.0.0` release.
> Add `SignextLowering` pass to `wasm-opt`

- Cargo.lock
- crates/build/Cargo.toml
- crates/build/src/lib.rs
- crates/build/src/wasm_opt.rs
- crates/cargo-contract/Cargo.toml
- crates/cargo-contract/src/cmd/extrinsics/call.rs
- crates/cargo-contract/src/cmd/extrinsics/error.rs
- crates/cargo-contract/src/cmd/extrinsics/events.rs
- crates/cargo-contract/src/cmd/extrinsics/instantiate.rs
- crates/cargo-contract/src/cmd/extrinsics/mod.rs
- crates/cargo-contract/src/cmd/extrinsics/remove.rs
- crates/cargo-contract/src/cmd/extrinsics/upload.rs
- crates/cargo-contract/src/cmd/runtime_api/mod.rs
- crates/transcode/Cargo.toml
Backport #1189 + #1280. Enables new toolchains > `1.69` + nodes with old `pallet_contracts` (pre `sign_ext` support)
**Edit**: Also had to manually backport subxt updates from #1149 and #1236 in order to fix compatibility issues with an old version of `sp-core` on which the current version of `subxt` depends. `wasmi-validation` does not expect the `sign-ext` instruction, but this dependency is removed in recent releases.
Can be released as `3.2.0`. Rel https://github.com/paritytech/cargo-contract/issues/1239
> Backport `SignextLowering` #1189 + #1280

- CHANGELOG.md
- crates/cargo-contract/src/cmd/info.rs
- crates/cargo-contract/src/cmd/mod.rs
- crates/cargo-contract/src/main.rs
- crates/extrinsics/src/error.rs
- crates/extrinsics/src/integration_tests.rs
- crates/extrinsics/src/lib.rs
- docs/info.md
Closes https://github.com/paritytech/cargo-contract/issues/797
- Output for command `cargo info -all` is:
```
5DpyotvcUDkFxTtHzkwR7Rqe37bdjc6M5Rxeiy57Gv2RQzp8
5GsoMKLTgFEpzHQTi7c4ZKCLZC6VxtHZxwMydSi79uemABez
```
- Flag combination --all --output-json outputs:
```
{
"contracts": [
"5DpyotvcUDkFxTtHzkwR7Rqe37bdjc6M5Rxeiy57Gv2RQzp8",
"5GsoMKLTgFEpzHQTi7c4ZKCLZC6VxtHZxwMydSi79uemABez"
]
}
```
- Flags combination --binary --all is forbidden
- Current implementation does not support response paging
> Add flag --all to cargo contract info

- crates/build/src/metadata.rs
The cause of the ink! CI failing https://github.com/paritytech/ink/pull/1921 was that there has been a recent change #1190 which passes `CARGO_ENCODED_RUSTFLAGS` when generating the metadata, thus overriding the `RUSTFLAGS` set in the environment.
> Add `-Clink-dead-code` to metadata gen `RUSTFLAGS`

- Cargo.lock
- crates/cargo-contract/Cargo.toml
- crates/extrinsics/Cargo.toml
- crates/extrinsics/src/lib.rs
Quick follow up to #1352 to use the patch release and the new `account_nonce` method to replace the copied impl.
> Use new `account_nonce` API from subxt `0.32.1`

- crates/extrinsics/src/contract_artifacts.rs
- crates/extrinsics/src/contract_info.rs
- crates/extrinsics/src/lib.rs
This PR simply moves related `contract_info` and `contract_artifacts` related code into their own files. The code and the crate API are unchanged.
The crate lib file had become too large, so this begins to split it up a bit.
> Refactor: extract `contract_info` and `contract_artifacts` mods from extrinsics root lib

- CHANGELOG.md
- crates/extrinsics/src/call.rs
- crates/extrinsics/src/integration_tests.rs
Related issue: https://github.com/paritytech/ink/issues/1969
`ink!` can't properly prevent messages supposed to be immutable from changing state regardless. Instead, we rely on the client and tooling to honor the `mutates` field in the metadata.
Without this change, cargo contract will happily execute messages like the one below. This message receives `&self` which signals it should be immutable. Other contract languages, e.g. Solidity, would refuse to compile this. Instead, we rely on the client to prevent it. The rogue balance transfer is just an illustration; Things like that might come from a rogue snippet or sit inside a rogue library.
```rust
#[ink(message)]
pub fn get(&self) -> bool {
// oops
self.env()
.transfer(self.env().caller(), self.env().balance())
.unwrap();
self.value
} …
```
> Prevent submitting calls to messages marked as immutable

- CHANGELOG.md
- Cargo.lock
- crates/cargo-contract/Cargo.toml
- crates/cargo-contract/src/cmd/mod.rs
- crates/cargo-contract/src/cmd/schema.rs
- crates/cargo-contract/src/main.rs
Closes #1090 and https://github.com/paritytech/ink/issues/1564
- [y] y/n | Is it dependent on the specific version of `ink` or `pallet-contracts`? - 5.0.0-alpha
Introudeces schema generation and verfication commands.
This PR automated proces for metadata schema generation.
Whenever there are changes to the schema, if `cargo-contract` targets the latest version of `ink_metadata` the scheme can be generated with `cargo contract schema-generate inner/outer`. This will print json to STDOUT.
And here is the sample of how to verify the metadata against specified schema file:
Bundle:
```
cargo contract verify-schema --schema /Users/skymanone/Projects/ink/crates/metadata/contract_schema.json --bundle target/ink/flipper.contract
Successfully verified …
```
> Add schema generation and verification

- CHANGELOG.md
- crates/cargo-contract/src/cmd/remove.rs
- crates/cargo-contract/src/cmd/upload.rs
This PR addresses an issue where the JSON output for both the `upload` and `remove` commands in cargo contract was in an invalid format.
This pull request enhances the JSON output for both the `upload` and `remove` commands in cargo contract.
Previously, the JSON output was in an invalid format, making it challenging to parse and extract information. The modified format now produces valid JSON objects for easier parsing.
```bash
// Invalid JSON Format (Before)
[
{
"pallet": "Balances",
"name": "Withdraw",
// ... Other fields
},
// ... Additional events
]
{
"code_hash": "0xe62b681614e6b7dbe892796b..."
}
```
```bash
// Valid JSON Format (After)
{
"code_hash": …
```
> Improve JSON Output for Upload and Remove Commands

- .github/workflows/release-image.yml
Fix Docker image creation on release
The Docker image tag was expanded too late, and the environment variable used at that point was not present.
- [y] My code follows the style guidelines of this project
- [n] I have added an entry to `CHANGELOG.md`
- [n] I have commented my code, particularly in hard-to-understand areas
- [n] I have added tests that prove my fix is effective or that my feature works
- [y] Any dependent changes have been merged and published in downstream modules
> Fix docker image release

- Cargo.lock
- crates/cargo-contract/Cargo.toml
- crates/extrinsics/Cargo.toml
- crates/extrinsics/src/lib.rs
- Use low level API to replace `wait_for_in_block`, see https://github.com/paritytech/subxt/pull/1237.
- Implicitly updates the MCRV to `1.74` see https://github.com/paritytech/subxt/pull/1299
Supersedes #1421 and #1422.
> Update `subxt` to `0.33.0`

- Cargo.lock
- crates/cargo-contract/Cargo.toml
- crates/cargo-contract/src/cmd/call.rs
- crates/cargo-contract/src/cmd/mod.rs
- crates/extrinsics/Cargo.toml
- crates/extrinsics/src/call.rs
- crates/extrinsics/src/instantiate.rs
- crates/extrinsics/src/lib.rs
- crates/extrinsics/src/pallet_contracts_primitives.rs
- crates/extrinsics/src/upload.rs
- crates/transcode/Cargo.toml
Initially this PR began with updating the version of `subxt` to `0.34`, and the updating of the related substrate dependencies. 
However, the `pallet_contracts_primitives` crate is no longer published, so this PR creates local copies of the required types used mainly for the results of dry-run extrinsic RPC calls.
> Replace legacy `pallet_contracts_primitives` with local types

- build-image/Dockerfile
Remove `linting` dependencies
The Docker image is used for release builds with an older stable compiler, which doesn't allow us to build the linting dependencies. However, for the current release, we can entirely disable it, since the linter is optional for the Wasm target.
- (n/a) My code follows the style guidelines of this project
- (n/a) I have added an entry to `CHANGELOG.md`
- (n/a) I have commented my code, particularly in hard-to-understand areas
- (n/a) I have added tests that prove my fix is effective or that my feature works
> fix(docker): Remove `linting` dependencies

- Cargo.lock
- crates/build/Cargo.toml
- crates/build/src/docker.rs
The `users` dep is no longer maintained, someone forked it to the `uzers` crate and maintains it there now. Details [here](https://github.com/ogham/rust-users/issues/54#issuecomment-1686030024).
Will get rid of
* https://github.com/paritytech/cargo-contract/security/dependabot/21 
* https://github.com/paritytech/ink/security/dependabot/6
> Replace `users` dep with `uzers`

- CHANGELOG.md
- Cargo.lock
- crates/cargo-contract/Cargo.toml
- crates/cargo-contract/src/cmd/storage.rs
Closes #1484
Change storage table layout
Change storage table layout to:
> Add a new tabular layout for the contract storage data

- CHANGELOG.md
- crates/build/src/args.rs
- crates/cargo-contract/src/cmd/call.rs
- crates/extrinsics/src/call.rs
- crates/extrinsics/src/env_check.rs
- crates/extrinsics/src/extrinsic_opts.rs
- crates/extrinsics/src/instantiate.rs
- crates/extrinsics/src/lib.rs
- crates/extrinsics/src/upload.rs
> Print type comparison warning only on `--verbose`

- CHANGELOG.md
- crates/transcode/src/encode.rs
Closes https://github.com/paritytech/cargo-contract/issues/780.
Here's how it looks:
> Improve error message for expected String

- build-image/Dockerfile
- build-image/README.md
Closes #_
Fix build --verifiable
Cargo contract version `4.0.0-rc.2`
`cargo contract build --verifiable`
causes an issue:
```
[==] Checking clippy linting rules
error: 'cargo-clippy' is not installed for the toolchain 'stable-x86_64-unknown-linux-gnu'
To install, run `rustup component add clippy`
ERROR: 
ERROR: Failed to read build result from docker build
```
> Fix build --verifiable command

- crates/cargo-contract/src/cmd/build.rs
Closes #_
Disable flags combination: `cargo contract build --verifiable --lint`
Do not allow for lint option when running contract build in docker container
> Disable linter in docker container

- crates/metadata/src/byte_str.rs
- crates/metadata/src/compatibility.rs
- [] n | Does it introduce breaking changes?
- [] n | Is it dependent on the specific version of `ink` or `pallet-contracts`?
Previously the error message when using ver `4` of cargo contracts on contracts written in ink version `4.x` was to "update to cargo contract to 3.2" which is slightly confusing, since you actually have to downgrade then. The error message was adjusted.
> Make the error message on incompatible versions clearer

- CHANGELOG.md
- crates/transcode/src/lib.rs
Closes #1521 
This PR solves issue #1521
> Reexport ink_metadata in transcoder crate

- .github/workflows/release-image.yml
Closes #_
More info can be found in this issue: https://github.com/paritytech/ci_cd/issues/957
> [ci] Make publish docker action more secure

- .github/workflows/dependabot-auto-merge.yml
Closes #_
More details can be found in [this comment](https://github.com/paritytech/ci_cd/issues/957#issuecomment-1983192568)
> [ci] Run dependabot with app credentials

- .github/workflows/dependabot-auto-merge.yml
Closes #_
related to https://github.com/paritytech/ci_cd/issues/957
> [ci] pin versions for release-verifiable-image

- CHANGELOG.md
- crates/build/src/docker.rs
Closes #_
Remove docker container on build failure
It fixed an error where the docker container was left in an improper state after a build failure. 
When a failure occurred during contract build, the container was left in an improper state. So, even when the user attempted to compile the contract with the fix, the build still failed due to the incorrect container state after the first build.
> Remove docker container on build failure

- .github/workflows/dependabot-auto-merge.yml
Closes #_
PR changes dependabot auto-merge workflow so it can use default GITHUB_TOKEN from GitHub without additional dependencies and users.
cc https://github.com/paritytech/ci_cd/issues/957
> [ci] Change workflow for dependabot auto merge

- .github/workflows/ci.yml
- CHANGELOG.md
- crates/build/templates/new/_Cargo.toml
- crates/build/templates/new/lib.rs
Closes #_
Fix e2e tests in the contract template
ink e2e tests were not updated to version 5, causing failures when executing the following commands
```
cargo contract new hehe
cargo test --release --features e2e-tests
```
> Fix e2e tests in the contract template

- CHANGELOG.md
- crates/cargo-contract/src/cmd/verify.rs
- crates/cargo-contract/tests/verify.rs
Closes #1539
Adds a raw verification of the contract against the reference wasm binary.
The command executes the code in the `Release` mode by default and then compares the wasm output with the reference contract.
> Verify raw Wasm in `cargo contract verify`

- crates/cargo-contract/src/cmd/info.rs
- crates/cargo-contract/src/cmd/mod.rs
- crates/cargo-contract/src/cmd/rpc.rs
- crates/extrinsics/src/contract_artifacts.rs
- crates/extrinsics/src/extrinsic_opts.rs
- crates/extrinsics/src/prod_chains.rs
Follow-up to https://github.com/paritytech/cargo-contract/pull/1290.
> Improvements for production deployment check

- CHANGELOG.md
- crates/cargo-contract/src/cmd/instantiate.rs
- crates/cargo-contract/src/cmd/mod.rs
- crates/cargo-contract/src/cmd/storage.rs
- crates/extrinsics/src/call.rs
- crates/extrinsics/src/contract_storage.rs
- crates/extrinsics/src/instantiate.rs
- crates/extrinsics/src/pallet_contracts_primitives.rs
Closes #1563
Fix instantiate command
Add `cargo contract storage --version` command
> Fix the instantiate command for Substrate 0.9.42-based chains

- README.md
Closes #1578 
Closes #_
- [ n ] y/n | Does it introduce breaking changes?
- [ n ] y/n | Is it dependent on the specific version of `ink` or `pallet-contracts`?
Change path of the cargo-contract.svg and ink-squid.svg files to the absolute path to the github raw content
> Fix readme images #1578

- CHANGELOG.md
- crates/cargo-contract/src/cmd/build.rs
- crates/cargo-contract/src/cmd/mod.rs
- crates/cargo-contract/src/cmd/prod_chains.rs
> Misc fixes to texts

- crates/build/templates/new/lib.rs
Closes #_
Just a typo, repetition of "contract" word. 
- [y] My code follows the style guidelines of this project
- [n] I have added an entry to `CHANGELOG.md`
- [y] I have commented my code, particularly in hard-to-understand areas
- [y] I have added tests that prove my fix is effective or that my feature works
- [y] Any dependent changes have been merged and published in downstream modules
> Fixing Flipper template typo

- CHANGELOG.md
- README.md
- build-image/Dockerfile
- crates/build/src/lib.rs
See: https://github.com/paritytech/ink/pull/2112
- [y] y/n | Is it dependent on the specific version of `ink` or `pallet-contracts`?
- [n/a] I have added tests that prove my fix is effective or that my feature works
> chore: Update toolchain for `ink_linting`

- .github/workflows/release-image.yml
- build-image/Dockerfile
Closes #_
Change image deployment path to `useink/contracts-verifiable`
Change `paritytech/contracts-verifiable` to `useink/contracts-verifiable`
> Add new image deployment repo

- build-image/README.md
- crates/build/src/docker.rs
- crates/build/src/lib.rs
Closes #_
Change verifiable image url
Image has been moved from `paritytech` to `useink`
> Switch to useink image in verifiable build command

- Cargo.lock
- crates/analyze/Cargo.toml
- crates/analyze/src/lib.rs
Closes #_
Replace unsupported `parity-wasm` crate with `wasmparser`
`parity-wasm` crate is unsupported, so it has been replaced with `wasmparser` crate
> Replace parity-wasm with wasmparser in analyze crate

- crates/build/templates/new/_Cargo.toml
- crates/build/templates/new/lib.rs
- crates/extrinsics/src/events.rs
Experimental PR for testing contracts deployed into pallet_revive 
- Updated the contract template to allow the generation of RISC-V compatible contracts using the pop new contract command.
- Address parsing event data: Improved event parsing functionality to correctly handle cases where the address type is H160.
> chore: improvements peter/feat-revive branch

- CHANGELOG.md
- crates/cargo-contract/src/cmd/config.rs
Supersedes https://github.com/use-ink/cargo-contract/pull/1743.
- [n] Does it introduce breaking changes?
- [n] Is it dependent on the specific version of `ink` or `pallet-contracts`?
If `cargo-contract` is installed with newer Rust versions this error will appear when using commands that interact with a chain (`instantiate`, `upload`, `call`, etc.).
User @dhilst reported this and took this screenshot:
The root of the error is that `stringify!` on paths like `crate::foo` can yield either `crate :: foo` (with spaces, in newer Rust versions) or `crate::foo` (without spaces, in older Rust versions). See https://github.com/rust-lang/rust/issues/128992 for more details.
The merge of this behavior into Rust `master` occurred in https://github.com/rust-lang/rust/pull/125174 on June 12. Nightlies …
> Fix "chain configuration not found" error

- README.md
- build-image/Dockerfile
- crates/build/src/lib.rs
References https://github.com/use-ink/ink/pull/2280.
> Update to latest dylint toolchain update in `ink` repo

- Cargo.lock
- crates/cargo-contract/Cargo.toml
- crates/cargo-contract/src/cmd/schema.rs
Supersedes https://github.com/use-ink/cargo-contract/pull/1804.
> Upgrade `jsonschema` dependency to v26

- CHANGELOG.md
- crates/cargo-contract/src/cmd/config.rs
Fixes the "chain configuration not found" issue on Rust 1.79, as reported by @Lohann in https://github.com/use-ink/cargo-contract/pull/1743.
I'll backport to a 4.1.2 release.
> Handle case of Rust 1.79 behavior of stringify! on crate path

- CHANGELOG.md
- crates/cargo-contract/Cargo.toml
- crates/cargo-contract/src/cmd/verify.rs
How the new output formatting looks:
I did a drive-by improvement of the output format of `cargo-contract` version mismatches:
> Validate externally passed Rust toolchain identifiers

- CHANGELOG.md
- crates/extrinsics/src/extrinsic_calls.rs
- crates/extrinsics/src/lib.rs
- crates/extrinsics/src/upload.rs
Closes #_
- [n] y/n | Is it dependent on the specific version of `ink` or `pallet-contracts`? (uses pallet-contracts)
These types provide useful code for managing Subxt interactions with pallet-contracts. Exposing them allows reuse in other crates, while still allowing the crates to have flexibility and manage the submission of the transaction.
> Make extrinsic call types, upload, and events public

- CHANGELOG.md
- crates/build/src/lib.rs
Closes #_ (N/A)
Enables clippy lints for overflowing (and lossy) integer type cast operations (i.e. `as` conversions)
[#1190 "Disallow[ed] unchecked arithmetic"](https://github.com/use-ink/cargo-contract/pull/1190), but from [this comment](https://github.com/paritytech/cargo-contract/pull/1190/files#diff-b18d9ef02a8395df7dcf8cc2d999cc16fe1fefe5b2151dfbd763f8b65e0c778dR465-R466), it looks like the actual intent was to "guarantee that implicit overflows never happen", if that's the case then like the `-C overflow-checks` for `rustc`, `-Dclippy::arithmetic_side_effects` is actually NOT sufficient.
This is because type cast operations (i.e. `as` conversions) can …
> Deny overflowing (and lossy) integer type cast operations

- CHANGELOG.md
- crates/build/src/workspace/manifest.rs
- crates/build/templates/new/_Cargo.toml
Closes #_ (N/A)
Update `Cargo.toml` template used by new contract command (i.e. `cargo contract new <my_contract>`) to use latest crates.io version for `ink` and `ink_e2e` dependencies ~~instead of git dependencies~~.
Update `Cargo.toml` template used by new contract command (i.e. `cargo contract new <my_contract>`) to use latest crates.io version for `ink` and `ink_e2e` dependencies ~~instead of git dependencies~~.
> Use ink! release version in new contract template

- CHANGELOG.md
- Cargo.lock
- crates/build/Cargo.toml
- crates/build/README.md
- crates/build/src/args.rs
- crates/build/src/crate_metadata.rs
- crates/build/src/docker.rs
- crates/build/src/lib.rs
- crates/build/src/metadata.rs
- crates/build/src/solidity_metadata.rs
- crates/build/src/solidity_metadata/abi.rs
- crates/build/src/solidity_metadata/natspec.rs
- crates/build/src/tests.rs
- crates/build/templates/generate-metadata/main.rs
- crates/cargo-contract/src/cmd/build.rs
- crates/cargo-contract/src/cmd/verify.rs
- crates/metadata/src/lib.rs
Closes #1070 
Also closes https://github.com/use-ink/ink-alliance/issues/13
- [y] y/n | Does it introduce breaking changes?
Adds option to generate Solidity compatible metadata files
- Adds a CLI arg `cargo contract build --metadata <ink|solidity>` for choosing the specification to use for metadata generation
- Adds ability to generate Solidity compatible [ABI](https://docs.soliditylang.org/en/latest/abi-spec.html#json) and [metadata](https://docs.soliditylang.org/en/latest/metadata.html) files (i.e. `<artifact_name>.abi` and `<artifact_name>.json`)
> Generate Solidity compatible metadata 

- crates/build/src/workspace/profile.rs
There's a bunch of bugs in `polkavm` currently. We should revert this commit once some of those are fixed and see if we can bring `Lto::Fat` back.
> Revert me: Force `Lto::Off`

- crates/build/src/lib.rs
https://github.com/paritytech/parity-scale-codec/issues/713
> Revert me: Disable clippy `cast_possible_truncation`

- Cargo.lock
- crates/build/Cargo.toml
- crates/build/templates/new/_Cargo.toml
- crates/cargo-contract/Cargo.toml
- crates/extrinsics/Cargo.toml
- crates/transcode/Cargo.toml
Update dependencies to 2503 qne import the latests versions released in crates.io.
- polkavm-linker to "0.22.0"
https://github.com/use-ink/ink-alliance/issues/50
Note: Once this PR https://github.com/use-ink/ink/pull/2478 is merged and the `ink_metadata`, `ink`, `ink_e2e`, and `ink_env` crates are published, this PR should be updated to reference the newly released versions. After that, it will be ready to merge.
> chore: update dependencies

- CHANGELOG.md
- build-image/Dockerfile
- build-image/README.md
- crates/build/src/lint.rs
Dated manifest at specified revision causes compilation issues.
- [n] y/n | Is it dependent on the specific version of `ink` or `pallet-contracts`? Not specifically, but it does update the revision of the linting crate to`5dc1624c3fa279cc57b4418b939cc089790f42f0` to resolve the build issues experienced.
Resolves the [CI build issues](https://github.com/use-ink/cargo-contract/actions/workflows/release-image.yml) of the `release-verifiable-image` workflow, which were due to the linting function pointing to an ink commit with a broken manifest.
Updates the commit of the linting crate to `5dc1624c3fa279cc57b4418b939cc089790f42f0`, which is after standardising on `stable2503` of the Polkadot SDK. 
Updates the base image to `debian:stable-slim` …
> fix: verifiable image build

- Cargo.lock
- crates/build/Cargo.toml
- crates/build/templates/new/_Cargo.toml
- crates/cargo-contract/Cargo.toml
- crates/extrinsics/Cargo.toml
- crates/transcode/Cargo.toml
Update ink! dependencies to target the` v6.0.0-alpha` release.
Test are failing because this line: https://github.com/use-ink/cargo-contract/pull/2026/files#diff-955d62dc3113f168fa64fe7ba020dc0a0837d43fed594fa73fbccbb5b72f4a0cL11
`ink_e2e = "6.0.0-alpha"`
The crate `ink_e2e` will be released after cargo-contract is published because `ink_e2e` is dependent on the `cargo-contract` crates.  https://github.com/use-ink/ink/blob/master/RELEASES_CHECKLIST.md?plain=1#L57
So the steps will be:
- First I am going to release `cargo-contracts`.
- Update the dependency https://github.com/use-ink/ink/blob/master/Cargo.toml#L41 in https://github.com/use-ink/ink/pull/2498
-  Release `ink_e2e`
> chore: update ink dependencies

- CHANGELOG.md
- crates/build/src/crate_metadata.rs
Closes #_
`cargo-contract` erroneously emits the warning below about "[lib] name" in `Cargo.toml` for all contracts that include a hyphen in the package name, even when no name is specified in the `[lib]` section.
This is because if no "[lib] name" is specified, cargo "normalizes" the package name and auto inserts it as the lib name. The code that emits this warning currently doesn't take this into consideration (especially the "normalization" part) and hence emits this warning erroneously for hyphenated package names.
This PR fixes the this behavior by comparing the "[lib] name" retrieved from `cargo metadata` to the normalized package name before emitting …
> fix: erroneous "[lib] name" warnings

- CHANGELOG.md
- Cargo.lock
- crates/build/Cargo.toml
- crates/build/templates/new/_Cargo.toml
- crates/cargo-contract/Cargo.toml
- crates/cargo-contract/src/cmd/account.rs
- crates/cargo-contract/src/cmd/call.rs
- crates/cargo-contract/src/cmd/config.rs
- crates/cargo-contract/src/cmd/info.rs
- crates/cargo-contract/src/cmd/instantiate.rs
- crates/cargo-contract/src/cmd/mod.rs
- crates/cargo-contract/src/cmd/remove.rs
- crates/cargo-contract/src/cmd/storage.rs
- crates/cargo-contract/src/cmd/upload.rs
- crates/extrinsics/Cargo.toml
- crates/extrinsics/src/contract_info.rs
- crates/extrinsics/src/contract_storage.rs
- crates/extrinsics/src/events.rs
- crates/extrinsics/src/instantiate.rs
- crates/extrinsics/src/lib.rs
- crates/extrinsics/src/map_account.rs
- crates/extrinsics/src/remove.rs
- crates/extrinsics/src/rpc.rs
- crates/extrinsics/src/upload.rs
- crates/transcode/Cargo.toml
As per https://github.com/use-ink/ink-alliance/issues/42, updates subxt to the latest version, addressing breaking changes in the least intrusive way possible.
- [N ] y/n | Does it introduce breaking changes?
- [Y] y/n | Is it dependent on the specific version of `ink` or `pallet-contracts`? Yes, it requires a version with the same subxt updates, which is currently available at https://github.com/use-ink/ink/pull/2504. The dependencies will be updated once that PR is merged to conclude the completion of this PR.
The following breaking changes affected the codebase:
- Removal of `substrate-compat` feature in https://github.com/paritytech/subxt/releases/tag/v0.39.0. The ink crates now control the version of `sp-core`/`sp-runtime` as required. `num-traits` dependency added for `Zero` trait …
> refactor(deps): update subxt and address breaking changes

- CHANGELOG.md
- crates/build/templates/rustc_wrapper/_Cargo.toml
Follow up to https://github.com/use-ink/cargo-contract/pull/2033
In ink!'s CI, the `rustc` wrapper crate can end up in a directory structure where `cargo` "believes" it's a workspace member, causing its compilation to fail.
This PR explicitly marks the `rustc` wrapper crate as a non-member of any workspace by adding an empty `[workspace]` table to its manifest.
> Mark `rustc` wrapper crate as a non-member of any workspace

- CHANGELOG.md
- Cargo.lock
- crates/build/Cargo.toml
- crates/build/src/crate_metadata.rs
- crates/build/src/lib.rs
- crates/build/src/lint.rs
- crates/build/src/util/mod.rs
- crates/build/src/util/rustc_wrapper.rs
Follow up to https://github.com/use-ink/cargo-contract/pull/2033
- Makes `rustc` wrapper reusable across a build via an env var
- Exposes `rustc` wrapper and ABI parsing utilities in public interface
> refactor: Reusable `rustc` wrapper

- CHANGELOG.md
- crates/build/templates/new/_Cargo.toml
Follow up to #2033 
Silences `unexpected_cfg` warnings ([see details](https://blog.rust-lang.org/2024/05/06/check-cfg/#expecting-custom-cfgs)) when "directly" running cargo subcommands (e.g. `cargo clippy`).
See https://github.com/use-ink/ink/issues/2479 for details about the `ink_abi` `cfg` flag.
> Declare `ink_abi` as an expected `cfg` in new project `Cargo.toml` template

- CHANGELOG.md
- crates/build/src/args.rs
- crates/build/src/crate_metadata.rs
- crates/build/src/docker.rs
- crates/build/src/lib.rs
- crates/build/src/solidity_metadata.rs
- crates/build/src/solidity_metadata/abi.rs
- crates/cargo-contract/src/cmd/build.rs
Related to https://github.com/use-ink/ink/issues/2520
- [y] y/n | Does it introduce breaking changes?
- Allow setting target directory for contract builds by introducing a `target_dir` field in `ExecutionArgs`
- This is currently intended to allow e2e tests infra to share intermediate build artifacts across all contract dependency builds ([see details](https://github.com/use-ink/ink/issues/2520)), so it's currently not exposed as a CLI arg
- Share target directory for intermediate build artifacts for contracts in workspaces (similar to how `cargo` handles target directory in workspaces)
- Introduces an `artifact_directory` field in `CrateMetadata` allowing only the final build artifacts (i.e. contract …
> Allow setting target directory for contract builds

- CHANGELOG.md
- crates/cargo-contract/src/cmd/mod.rs
- crates/extrinsics/src/lib.rs
- crates/extrinsics/src/map_account.rs
Closes #_
Linked to the issue: https://github.com/use-ink/cargo-contract/issues/1990
This PR updates the `map_account_dry_run` method to return the `partial_fee_estimation` before the user confirm wether to map the account or not.
> feat(cargo-contract): display fee estimation on map account dry-run

- CHANGELOG.md
- crates/build/src/solidity_metadata/abi.rs
Closes #_
Overloaded functions and events were previously being "deduplicated" by name
> Fix Solidity metadata generation for overloaded functions and events

- CHANGELOG.md
- Cargo.lock
- crates/cargo-contract/src/cmd/config.rs
- crates/extrinsics/src/env_check.rs
Follow up to https://github.com/use-ink/ink/pull/2622
- [y] y/n | Is it dependent on the specific version of `ink` or `pallet-contracts`?
See https://github.com/use-ink/ink/issues/2601 for details
> Remove `MAX_EVENT_TOPICS` from `Environment` implementations

- crates/cargo-contract/src/cmd/call.rs
- crates/cargo-contract/src/cmd/instantiate.rs
Closes https://github.com/use-ink/cargo-contract/issues/2105.
Here's how it looks for a contract  where the instructor is called with `true`:
```rust
#[ink(constructor)]
pub fn new(init_value: bool) -> Self {
assert!(!init_value);
Self { value: init_value }
}
```
And here for a contract with this message:
```rust
#[ink(message)]
pub fn flip(&mut self) {
panic!("oh no, something went wrong");
self.value = !self.value;
}
```
> Display payload of a contract revert
